import type { CompanyProfile } from "@/lib/companies/types";

/**
 * DAX issuers in STOXX rank order.
 *
 * Membership: public DAX selection list `slpublic_daxk_20260902.csv`
 * (Index Membership = DAXK, 40 constituents).
 * STOXX announced on 3 September 2026 that the DAX had no adjustments;
 * that review became effective on 21 September 2026.
 * One security per issuer. Volkswagen and Henkel are the preferred lines
 * that the index actually contains (VOW3 and HEN3).
 * Country is the STOXX issuer country, not a guessed headquarters.
 * Websites are the companies' corporate sites. Sector is omitted because
 * the selection list does not publish one.
 */
export const DAX40_COMPANIES = [
  {
    slug: "siemens",
    name: "Siemens",
    displayName: "Siemens",
    ticker: "SIE",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "siemens.com",
    websiteUrl: "https://www.siemens.com",
    tradingViewSymbol: "XETR:SIE",
    marketDataSymbol: "SIE.DE",
    logoPath: null,
    aliases: ["Siemens", "Siemens AG"],
    tickerAliases: ["SIE", "SIE.DE"],
  },
  {
    slug: "sap",
    name: "SAP",
    displayName: "SAP",
    ticker: "SAP",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "sap.com",
    websiteUrl: "https://www.sap.com",
    tradingViewSymbol: "XETR:SAP",
    marketDataSymbol: "SAP.DE",
    logoPath: null,
    aliases: ["SAP", "SAP SE"],
    tickerAliases: ["SAP", "SAP.DE"],
  },
  {
    slug: "allianz",
    name: "Allianz",
    displayName: "Allianz",
    ticker: "ALV",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "allianz.com",
    websiteUrl: "https://www.allianz.com",
    tradingViewSymbol: "XETR:ALV",
    marketDataSymbol: "ALV.DE",
    logoPath: null,
    aliases: ["Allianz", "Allianz SE"],
    tickerAliases: ["ALV", "ALV.DE"],
  },
  {
    slug: "siemens-energy",
    name: "Siemens Energy",
    displayName: "Siemens Energy",
    ticker: "ENR",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "siemens-energy.com",
    websiteUrl: "https://www.siemens-energy.com",
    tradingViewSymbol: "XETR:ENR",
    marketDataSymbol: "ENR.DE",
    logoPath: null,
    aliases: ["Siemens Energy", "Siemens Energy AG"],
    tickerAliases: ["ENR", "ENR.DE"],
  },
  {
    slug: "airbus",
    name: "Airbus",
    displayName: "Airbus",
    ticker: "AIR",
    exchange: "Xetra",
    countryCode: "NL",
    countryName: "Nederländerna",
    websiteLabel: "airbus.com",
    websiteUrl: "https://www.airbus.com",
    tradingViewSymbol: "XETR:AIR",
    marketDataSymbol: "AIR.DE",
    logoPath: null,
    aliases: ["Airbus", "Airbus SE"],
    tickerAliases: ["AIR", "AIR.DE"],
  },
  {
    slug: "deutsche-telekom",
    name: "Deutsche Telekom",
    displayName: "Deutsche Telekom",
    ticker: "DTE",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "telekom.com",
    websiteUrl: "https://www.telekom.com",
    tradingViewSymbol: "XETR:DTE",
    marketDataSymbol: "DTE.DE",
    logoPath: null,
    aliases: ["Deutsche Telekom", "Deutsche Telekom AG"],
    tickerAliases: ["DTE", "DTE.DE"],
  },
  {
    slug: "infineon",
    name: "Infineon",
    displayName: "Infineon",
    ticker: "IFX",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "infineon.com",
    websiteUrl: "https://www.infineon.com",
    tradingViewSymbol: "XETR:IFX",
    marketDataSymbol: "IFX.DE",
    logoPath: null,
    aliases: ["Infineon", "Infineon Technologies"],
    tickerAliases: ["IFX", "IFX.DE"],
  },
  {
    slug: "munich-re",
    name: "Münchener Rück",
    displayName: "Munich Re",
    ticker: "MUV2",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "munichre.com",
    websiteUrl: "https://www.munichre.com",
    tradingViewSymbol: "XETR:MUV2",
    marketDataSymbol: "MUV2.DE",
    logoPath: null,
    aliases: ["Münchener Rück", "Munich Re", "Muenchener Rueck"],
    tickerAliases: ["MUV2", "MUV2.DE"],
  },
  {
    slug: "deutsche-bank",
    name: "Deutsche Bank",
    displayName: "Deutsche Bank",
    ticker: "DBK",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "db.com",
    websiteUrl: "https://www.db.com",
    tradingViewSymbol: "XETR:DBK",
    marketDataSymbol: "DBK.DE",
    logoPath: null,
    aliases: ["Deutsche Bank", "Deutsche Bank AG"],
    tickerAliases: ["DBK", "DBK.DE"],
  },
  {
    slug: "rheinmetall",
    name: "Rheinmetall",
    displayName: "Rheinmetall",
    ticker: "RHM",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "rheinmetall.com",
    websiteUrl: "https://www.rheinmetall.com",
    tradingViewSymbol: "XETR:RHM",
    marketDataSymbol: "RHM.DE",
    logoPath: null,
    aliases: ["Rheinmetall", "Rheinmetall AG"],
    tickerAliases: ["RHM", "RHM.DE"],
  },
  {
    slug: "dhl",
    name: "DHL Group",
    displayName: "DHL",
    ticker: "DHL",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "group.dhl.com",
    websiteUrl: "https://www.group.dhl.com",
    tradingViewSymbol: "XETR:DHL",
    marketDataSymbol: "DHL.DE",
    logoPath: null,
    aliases: ["DHL Group", "DHL", "Deutsche Post", "DHL AG"],
    tickerAliases: ["DHL", "DHL.DE"],
  },
  {
    slug: "deutsche-boerse",
    name: "Deutsche Börse",
    displayName: "Deutsche Börse",
    ticker: "DB1",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "deutsche-boerse.com",
    websiteUrl: "https://www.deutsche-boerse.com",
    tradingViewSymbol: "XETR:DB1",
    marketDataSymbol: "DB1.DE",
    logoPath: null,
    aliases: ["Deutsche Börse", "Deutsche Boerse"],
    tickerAliases: ["DB1", "DB1.DE"],
  },
  {
    slug: "bayer",
    name: "Bayer",
    displayName: "Bayer",
    ticker: "BAYN",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "bayer.com",
    websiteUrl: "https://www.bayer.com",
    tradingViewSymbol: "XETR:BAYN",
    marketDataSymbol: "BAYN.DE",
    logoPath: null,
    aliases: ["Bayer", "Bayer AG"],
    tickerAliases: ["BAYN", "BAYN.DE"],
  },
  {
    slug: "basf",
    name: "BASF",
    displayName: "BASF",
    ticker: "BAS",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "basf.com",
    websiteUrl: "https://www.basf.com",
    tradingViewSymbol: "XETR:BAS",
    marketDataSymbol: "BAS.DE",
    logoPath: null,
    aliases: ["BASF", "BASF SE"],
    tickerAliases: ["BAS", "BAS.DE"],
  },
  {
    slug: "eon",
    name: "E.ON",
    displayName: "E.ON",
    ticker: "EOAN",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "eon.com",
    websiteUrl: "https://www.eon.com",
    tradingViewSymbol: "XETR:EOAN",
    marketDataSymbol: "EOAN.DE",
    logoPath: null,
    aliases: ["E.ON", "E.ON SE", "EON"],
    tickerAliases: ["EOAN", "EOAN.DE"],
  },
  {
    slug: "rwe",
    name: "RWE",
    displayName: "RWE",
    ticker: "RWE",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "rwe.com",
    websiteUrl: "https://www.rwe.com",
    tradingViewSymbol: "XETR:RWE",
    marketDataSymbol: "RWE.DE",
    logoPath: null,
    aliases: ["RWE", "RWE AG"],
    tickerAliases: ["RWE", "RWE.DE"],
  },
  {
    slug: "mercedes-benz",
    name: "Mercedes-Benz Group",
    displayName: "Mercedes-Benz",
    ticker: "MBG",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "group.mercedes-benz.com",
    websiteUrl: "https://group.mercedes-benz.com",
    tradingViewSymbol: "XETR:MBG",
    marketDataSymbol: "MBG.DE",
    logoPath: null,
    aliases: ["Mercedes-Benz Group", "Mercedes-Benz", "Mercedes Benz"],
    tickerAliases: ["MBG", "MBG.DE"],
  },
  {
    slug: "adidas",
    name: "Adidas",
    displayName: "Adidas",
    ticker: "ADS",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "adidas-group.com",
    websiteUrl: "https://www.adidas-group.com",
    tradingViewSymbol: "XETR:ADS",
    marketDataSymbol: "ADS.DE",
    logoPath: null,
    aliases: ["Adidas", "adidas AG"],
    tickerAliases: ["ADS", "ADS.DE"],
  },
  {
    slug: "daimler-truck",
    name: "Daimler Truck",
    displayName: "Daimler Truck",
    ticker: "DTG",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "daimlertruck.com",
    websiteUrl: "https://www.daimlertruck.com",
    tradingViewSymbol: "XETR:DTG",
    marketDataSymbol: "DTG.DE",
    logoPath: null,
    aliases: ["Daimler Truck", "Daimler Truck Holding"],
    tickerAliases: ["DTG", "DTG.DE"],
  },
  {
    slug: "heidelberg-materials",
    name: "Heidelberg Materials",
    displayName: "Heidelberg Materials",
    ticker: "HEI",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "heidelbergmaterials.com",
    websiteUrl: "https://www.heidelbergmaterials.com",
    tradingViewSymbol: "XETR:HEI",
    marketDataSymbol: "HEI.DE",
    logoPath: null,
    aliases: ["Heidelberg Materials", "HeidelbergCement"],
    tickerAliases: ["HEI", "HEI.DE"],
  },
  {
    slug: "mtu",
    name: "MTU Aero Engines",
    displayName: "MTU Aero Engines",
    ticker: "MTX",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "mtu.de",
    websiteUrl: "https://www.mtu.de",
    tradingViewSymbol: "XETR:MTX",
    marketDataSymbol: "MTX.DE",
    logoPath: null,
    aliases: ["MTU Aero Engines", "MTU"],
    tickerAliases: ["MTX", "MTX.DE"],
  },
  {
    slug: "bmw",
    name: "BMW",
    displayName: "BMW",
    ticker: "BMW",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "bmwgroup.com",
    websiteUrl: "https://www.bmwgroup.com",
    tradingViewSymbol: "XETR:BMW",
    marketDataSymbol: "BMW.DE",
    logoPath: null,
    aliases: ["BMW", "Bayerische Motoren Werke"],
    tickerAliases: ["BMW", "BMW.DE"],
  },
  {
    slug: "fresenius",
    name: "Fresenius",
    displayName: "Fresenius",
    ticker: "FRE",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "fresenius.com",
    websiteUrl: "https://www.fresenius.com",
    tradingViewSymbol: "XETR:FRE",
    marketDataSymbol: "FRE.DE",
    logoPath: null,
    aliases: ["Fresenius", "Fresenius SE"],
    tickerAliases: ["FRE", "FRE.DE"],
  },
  {
    slug: "merck-kgaa",
    name: "Merck KGaA",
    displayName: "Merck",
    ticker: "MRK",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "merckgroup.com",
    websiteUrl: "https://www.merckgroup.com",
    tradingViewSymbol: "XETR:MRK",
    marketDataSymbol: "MRK.DE",
    logoPath: null,
    aliases: ["Merck KGaA", "Merck", "Merck Group"],
    tickerAliases: ["MRK", "MRK.DE"],
  },
  {
    slug: "commerzbank",
    name: "Commerzbank",
    displayName: "Commerzbank",
    ticker: "CBK",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "commerzbank.de",
    websiteUrl: "https://www.commerzbank.de",
    tradingViewSymbol: "XETR:CBK",
    marketDataSymbol: "CBK.DE",
    logoPath: null,
    aliases: ["Commerzbank", "Commerzbank AG"],
    tickerAliases: ["CBK", "CBK.DE"],
  },
  {
    slug: "volkswagen",
    name: "Volkswagen",
    displayName: "Volkswagen",
    ticker: "VOW3",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "volkswagen-group.com",
    websiteUrl: "https://www.volkswagen-group.com",
    tradingViewSymbol: "XETR:VOW3",
    marketDataSymbol: "VOW3.DE",
    logoPath: null,
    aliases: ["Volkswagen", "Volkswagen AG", "VW"],
    tickerAliases: ["VOW3", "VOW3.DE"],
  },
  {
    slug: "hannover-re",
    name: "Hannover Rück",
    displayName: "Hannover Rück",
    ticker: "HNR1",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "hannover-re.com",
    websiteUrl: "https://www.hannover-re.com",
    tradingViewSymbol: "XETR:HNR1",
    marketDataSymbol: "HNR1.DE",
    logoPath: null,
    aliases: ["Hannover Rück", "Hannover Re", "Hannover Rueck"],
    tickerAliases: ["HNR1", "HNR1.DE"],
  },
  {
    slug: "vonovia",
    name: "Vonovia",
    displayName: "Vonovia",
    ticker: "VNA",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "vonovia.com",
    websiteUrl: "https://www.vonovia.com",
    tradingViewSymbol: "XETR:VNA",
    marketDataSymbol: "VNA.DE",
    logoPath: null,
    aliases: ["Vonovia", "Vonovia SE"],
    tickerAliases: ["VNA", "VNA.DE"],
  },
  {
    slug: "siemens-healthineers",
    name: "Siemens Healthineers",
    displayName: "Siemens Healthineers",
    ticker: "SHL",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "siemens-healthineers.com",
    websiteUrl: "https://www.siemens-healthineers.com",
    tradingViewSymbol: "XETR:SHL",
    marketDataSymbol: "SHL.DE",
    logoPath: null,
    aliases: ["Siemens Healthineers", "Siemens Healthineers AG"],
    tickerAliases: ["SHL", "SHL.DE"],
  },
  {
    slug: "symrise",
    name: "Symrise",
    displayName: "Symrise",
    ticker: "SY1",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "symrise.com",
    websiteUrl: "https://www.symrise.com",
    tradingViewSymbol: "XETR:SY1",
    marketDataSymbol: "SY1.DE",
    logoPath: null,
    aliases: ["Symrise", "Symrise AG"],
    tickerAliases: ["SY1", "SY1.DE"],
  },
  {
    slug: "henkel",
    name: "Henkel",
    displayName: "Henkel",
    ticker: "HEN3",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "henkel.com",
    websiteUrl: "https://www.henkel.com",
    tradingViewSymbol: "XETR:HEN3",
    marketDataSymbol: "HEN3.DE",
    logoPath: null,
    aliases: ["Henkel", "Henkel AG"],
    tickerAliases: ["HEN3", "HEN3.DE"],
  },
  {
    slug: "gea",
    name: "GEA Group",
    displayName: "GEA",
    ticker: "G1A",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "gea.com",
    websiteUrl: "https://www.gea.com",
    tradingViewSymbol: "XETR:G1A",
    marketDataSymbol: "G1A.DE",
    logoPath: null,
    aliases: ["GEA Group", "GEA"],
    tickerAliases: ["G1A", "G1A.DE"],
  },
  {
    slug: "fresenius-medical-care",
    name: "Fresenius Medical Care",
    displayName: "Fresenius Medical Care",
    ticker: "FME",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "freseniusmedicalcare.com",
    websiteUrl: "https://www.freseniusmedicalcare.com",
    tradingViewSymbol: "XETR:FME",
    marketDataSymbol: "FME.DE",
    logoPath: null,
    aliases: ["Fresenius Medical Care", "Fresenius Medical Care AG"],
    tickerAliases: ["FME", "FME.DE"],
  },
  {
    slug: "qiagen",
    name: "Qiagen",
    displayName: "Qiagen",
    ticker: "QIA",
    exchange: "Xetra",
    countryCode: "NL",
    countryName: "Nederländerna",
    websiteLabel: "qiagen.com",
    websiteUrl: "https://www.qiagen.com",
    tradingViewSymbol: "XETR:QIA",
    marketDataSymbol: "QIA.DE",
    logoPath: null,
    aliases: ["Qiagen", "Qiagen N.V."],
    tickerAliases: ["QIA", "QIA.DE"],
  },
  {
    slug: "hochtief",
    name: "Hochtief",
    displayName: "Hochtief",
    ticker: "HOT",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "hochtief.com",
    websiteUrl: "https://www.hochtief.com",
    tradingViewSymbol: "XETR:HOT",
    marketDataSymbol: "HOT.DE",
    logoPath: null,
    aliases: ["Hochtief"],
    tickerAliases: ["HOT", "HOT.DE"],
  },
  {
    slug: "continental",
    name: "Continental",
    displayName: "Continental",
    ticker: "CON",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "continental.com",
    websiteUrl: "https://www.continental.com",
    tradingViewSymbol: "XETR:CON",
    marketDataSymbol: "CON.DE",
    logoPath: null,
    aliases: ["Continental", "Continental AG"],
    tickerAliases: ["CON", "CON.DE"],
  },
  {
    slug: "brenntag",
    name: "Brenntag",
    displayName: "Brenntag",
    ticker: "BNR",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "brenntag.com",
    websiteUrl: "https://www.brenntag.com",
    tradingViewSymbol: "XETR:BNR",
    marketDataSymbol: "BNR.DE",
    logoPath: null,
    aliases: ["Brenntag", "Brenntag SE"],
    tickerAliases: ["BNR", "BNR.DE"],
  },
  {
    slug: "beiersdorf",
    name: "Beiersdorf",
    displayName: "Beiersdorf",
    ticker: "BEI",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "beiersdorf.com",
    websiteUrl: "https://www.beiersdorf.com",
    tradingViewSymbol: "XETR:BEI",
    marketDataSymbol: "BEI.DE",
    logoPath: null,
    aliases: ["Beiersdorf", "Beiersdorf AG"],
    tickerAliases: ["BEI", "BEI.DE"],
  },
  {
    slug: "scout24",
    name: "Scout24",
    displayName: "Scout24",
    ticker: "G24",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "scout24.com",
    websiteUrl: "https://www.scout24.com",
    tradingViewSymbol: "XETR:G24",
    marketDataSymbol: "G24.DE",
    logoPath: null,
    aliases: ["Scout24", "Scout24 SE"],
    tickerAliases: ["G24", "G24.DE"],
  },
  {
    slug: "zalando",
    name: "Zalando",
    displayName: "Zalando",
    ticker: "ZAL",
    exchange: "Xetra",
    countryCode: "DE",
    countryName: "Tyskland",
    websiteLabel: "corporate.zalando.com",
    websiteUrl: "https://corporate.zalando.com",
    tradingViewSymbol: "XETR:ZAL",
    marketDataSymbol: "ZAL.DE",
    logoPath: null,
    aliases: ["Zalando", "Zalando SE"],
    tickerAliases: ["ZAL", "ZAL.DE"],
  },
] as const satisfies readonly CompanyProfile[];
