import type { CompanyProfile } from "@/lib/companies/types";

/**
 * Nasdaq-100 issuers in official weighting order as of 25 September 2026.
 *
 * Source: Nasdaq Index Weighting for NDX, end of day 2026-09-25
 * (https://indexes.nasdaq.com/Index/Weighting/NDX).
 * Names, sectors and websites come from Nasdaq's company-profile endpoint
 * when that endpoint returns them. DoorDash has no profile payload there;
 * its name is normalized from the weighting security name. Honeywell
 * Aerospace and DoorDash have no website in that payload, so none is stored.
 * Country is the Nasdaq listing market (US). Nasdaq publishes a region, not
 * an ISO country, so issuer domicile is not guessed.
 * Alphabet Class A (GOOGL) is the canonical DivLab company. Class C (GOOG)
 * is the same issuer and is recorded only in NASDAQ100_SECURITIES.
 */
export const NASDAQ100_COMPANIES = [
  {
    slug: "apple",
    name: "Apple Inc.",
    displayName: "Apple",
    ticker: "AAPL",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "apple.com",
    websiteUrl: "https://www.apple.com",
    tradingViewSymbol: "NASDAQ:AAPL",
    marketDataSymbol: "AAPL",
    logoPath: null,
    aliases: ["Apple Inc.", "Apple"],
    tickerAliases: ["AAPL"],
  },
  {
    slug: "airbnb",
    name: "Airbnb, Inc.",
    displayName: "Airbnb",
    ticker: "ABNB",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "airbnb.com",
    websiteUrl: "https://www.airbnb.com",
    tradingViewSymbol: "NASDAQ:ABNB",
    marketDataSymbol: "ABNB",
    logoPath: null,
    aliases: ["Airbnb, Inc.", "Airbnb", "Airbnb, Inc Cl A Cmn"],
    tickerAliases: ["ABNB"],
  },
  {
    slug: "adobe",
    name: "Adobe Inc.",
    displayName: "Adobe",
    ticker: "ADBE",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "adobe.com",
    websiteUrl: "https://www.adobe.com",
    tradingViewSymbol: "NASDAQ:ADBE",
    marketDataSymbol: "ADBE",
    logoPath: null,
    aliases: ["Adobe Inc.", "Adobe"],
    tickerAliases: ["ADBE"],
  },
  {
    slug: "analog-devices",
    name: "Analog Devices, Inc.",
    displayName: "Analog Devices",
    ticker: "ADI",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "analog.com",
    websiteUrl: "https://www.analog.com",
    tradingViewSymbol: "NASDAQ:ADI",
    marketDataSymbol: "ADI",
    logoPath: null,
    aliases: ["Analog Devices, Inc.", "Analog Devices", "Analog Devices Cmn"],
    tickerAliases: ["ADI"],
  },
  {
    slug: "automatic-data-processing",
    name: "Automatic Data Processing, Inc.",
    displayName: "Automatic Data Processing",
    ticker: "ADP",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "adp.com",
    websiteUrl: "https://www.adp.com",
    tradingViewSymbol: "NASDAQ:ADP",
    marketDataSymbol: "ADP",
    logoPath: null,
    aliases: ["Automatic Data Processing, Inc.", "Automatic Data Processing", "Automatic Data Procs"],
    tickerAliases: ["ADP"],
  },
  {
    slug: "autodesk",
    name: "Autodesk, Inc.",
    displayName: "Autodesk",
    ticker: "ADSK",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "autodesk.com",
    websiteUrl: "https://www.autodesk.com",
    tradingViewSymbol: "NASDAQ:ADSK",
    marketDataSymbol: "ADSK",
    logoPath: null,
    aliases: ["Autodesk, Inc.", "Autodesk", "Autodesk Inc"],
    tickerAliases: ["ADSK"],
  },
  {
    slug: "american-electric-power",
    name: "American Electric Power Company, Inc.",
    displayName: "American Electric Power",
    ticker: "AEP",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Utilities",
    websiteLabel: "aep.com",
    websiteUrl: "https://www.aep.com",
    tradingViewSymbol: "NASDAQ:AEP",
    marketDataSymbol: "AEP",
    logoPath: null,
    aliases: ["American Electric Power Company, Inc.", "American Electric Power", "Amer Elc Pwr Co Cmn"],
    tickerAliases: ["AEP"],
  },
  {
    slug: "astera-labs",
    name: "Astera Labs, Inc.",
    displayName: "Astera Labs",
    ticker: "ALAB",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "asteralabs.com",
    websiteUrl: "https://www.asteralabs.com",
    tradingViewSymbol: "NASDAQ:ALAB",
    marketDataSymbol: "ALAB",
    logoPath: null,
    aliases: ["Astera Labs, Inc.", "Astera Labs"],
    tickerAliases: ["ALAB"],
  },
  {
    slug: "alnylam-pharmaceuticals",
    name: "Alnylam Pharmaceuticals, Inc.",
    displayName: "Alnylam Pharmaceuticals",
    ticker: "ALNY",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Health Care",
    websiteLabel: "alnylam.com",
    websiteUrl: "https://www.alnylam.com",
    tradingViewSymbol: "NASDAQ:ALNY",
    marketDataSymbol: "ALNY",
    logoPath: null,
    aliases: ["Alnylam Pharmaceuticals, Inc.", "Alnylam Pharmaceuticals", "Alnylam Pharmaceut"],
    tickerAliases: ["ALNY"],
  },
  {
    slug: "applied-materials",
    name: "Applied Materials, Inc.",
    displayName: "Applied Materials",
    ticker: "AMAT",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "appliedmaterials.com",
    websiteUrl: "https://www.appliedmaterials.com",
    tradingViewSymbol: "NASDAQ:AMAT",
    marketDataSymbol: "AMAT",
    logoPath: null,
    aliases: ["Applied Materials, Inc.", "Applied Materials"],
    tickerAliases: ["AMAT"],
  },
  {
    slug: "advanced-micro-devices",
    name: "Advanced Micro Devices, Inc.",
    displayName: "Advanced Micro Devices",
    ticker: "AMD",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "amd.com",
    websiteUrl: "https://www.amd.com",
    tradingViewSymbol: "NASDAQ:AMD",
    marketDataSymbol: "AMD",
    logoPath: null,
    aliases: ["Advanced Micro Devices, Inc.", "Advanced Micro Devices", "Adv Micro Devices"],
    tickerAliases: ["AMD"],
  },
  {
    slug: "amgen",
    name: "Amgen Inc.",
    displayName: "Amgen",
    ticker: "AMGN",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Health Care",
    websiteLabel: "amgen.com",
    websiteUrl: "https://www.amgen.com",
    tradingViewSymbol: "NASDAQ:AMGN",
    marketDataSymbol: "AMGN",
    logoPath: null,
    aliases: ["Amgen Inc.", "Amgen"],
    tickerAliases: ["AMGN"],
  },
  {
    slug: "amazon",
    name: "Amazon.com, Inc.",
    displayName: "Amazon",
    ticker: "AMZN",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "amazon.com",
    websiteUrl: "https://www.amazon.com",
    tradingViewSymbol: "NASDAQ:AMZN",
    marketDataSymbol: "AMZN",
    logoPath: null,
    aliases: ["Amazon.com, Inc.", "Amazon", "Amazon.com"],
    tickerAliases: ["AMZN"],
  },
  {
    slug: "applovin",
    name: "Applovin Corporation",
    displayName: "Applovin",
    ticker: "APP",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "applovin.com",
    websiteUrl: "https://www.applovin.com",
    tradingViewSymbol: "NASDAQ:APP",
    marketDataSymbol: "APP",
    logoPath: null,
    aliases: ["Applovin Corporation", "Applovin", "Applovin Corp Cla Cm"],
    tickerAliases: ["APP"],
  },
  {
    slug: "arm",
    name: "Arm Holdings plc",
    displayName: "Arm",
    ticker: "ARM",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "arm.com",
    websiteUrl: "https://www.arm.com",
    tradingViewSymbol: "NASDAQ:ARM",
    marketDataSymbol: "ARM",
    logoPath: null,
    aliases: ["Arm Holdings plc", "Arm", "Arm Holdings Plc Ads"],
    tickerAliases: ["ARM"],
  },
  {
    slug: "asml",
    name: "ASML Holding N.V.",
    displayName: "ASML",
    ticker: "ASML",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "asml.com",
    websiteUrl: "https://www.asml.com",
    tradingViewSymbol: "NASDAQ:ASML",
    marketDataSymbol: "ASML",
    logoPath: null,
    aliases: ["ASML Holding N.V.", "ASML", "Asml Hldg Ny Reg"],
    tickerAliases: ["ASML"],
  },
  {
    slug: "broadcom",
    name: "Broadcom Inc.",
    displayName: "Broadcom",
    ticker: "AVGO",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "broadcom.com",
    websiteUrl: "https://www.broadcom.com",
    tradingViewSymbol: "NASDAQ:AVGO",
    marketDataSymbol: "AVGO",
    logoPath: null,
    aliases: ["Broadcom Inc.", "Broadcom"],
    tickerAliases: ["AVGO"],
  },
  {
    slug: "axon-enterprise",
    name: "Axon Enterprise, Inc.",
    displayName: "Axon Enterprise",
    ticker: "AXON",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    websiteLabel: "axon.com",
    websiteUrl: "https://www.axon.com",
    tradingViewSymbol: "NASDAQ:AXON",
    marketDataSymbol: "AXON",
    logoPath: null,
    aliases: ["Axon Enterprise, Inc.", "Axon Enterprise", "Axon Enterprise, Inc"],
    tickerAliases: ["AXON"],
  },
  {
    slug: "booking-holdings",
    name: "Booking Holdings Inc.",
    displayName: "Booking",
    ticker: "BKNG",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "bookingholdings.com",
    websiteUrl: "https://www.bookingholdings.com",
    tradingViewSymbol: "NASDAQ:BKNG",
    marketDataSymbol: "BKNG",
    logoPath: null,
    aliases: ["Booking Holdings Inc.", "Booking", "Booking Holdings Inc"],
    tickerAliases: ["BKNG"],
  },
  {
    slug: "baker-hughes",
    name: "Baker Hughes Company",
    displayName: "Baker Hughes",
    ticker: "BKR",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "bakerhughes.com",
    websiteUrl: "https://www.bakerhughes.com",
    tradingViewSymbol: "NASDAQ:BKR",
    marketDataSymbol: "BKR",
    logoPath: null,
    aliases: ["Baker Hughes Company", "Baker Hughes", "Baker Hughes Co"],
    tickerAliases: ["BKR"],
  },
  {
    slug: "coca-cola-europacific-partners",
    name: "Coca-Cola Europacific Partners plc",
    displayName: "Coca-Cola Europacific Partners",
    ticker: "CCEP",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Staples",
    websiteLabel: "cocacolaep.com",
    websiteUrl: "https://www.cocacolaep.com",
    tradingViewSymbol: "NASDAQ:CCEP",
    marketDataSymbol: "CCEP",
    logoPath: null,
    aliases: ["Coca-Cola Europacific Partners plc", "Coca-Cola Europacific Partners", "Coca-Cola Europacifi"],
    tickerAliases: ["CCEP"],
  },
  {
    slug: "cadence-design-systems",
    name: "Cadence Design Systems, Inc.",
    displayName: "Cadence Design Systems",
    ticker: "CDNS",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "cadence.com",
    websiteUrl: "https://www.cadence.com",
    tradingViewSymbol: "NASDAQ:CDNS",
    marketDataSymbol: "CDNS",
    logoPath: null,
    aliases: ["Cadence Design Systems, Inc.", "Cadence Design Systems", "Cadence Design Sys"],
    tickerAliases: ["CDNS"],
  },
  {
    slug: "constellation-energy",
    name: "Constellation Energy Corporation",
    displayName: "Constellation Energy",
    ticker: "CEG",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Utilities",
    websiteLabel: "constellation.com",
    websiteUrl: "https://www.constellation.com",
    tradingViewSymbol: "NASDAQ:CEG",
    marketDataSymbol: "CEG",
    logoPath: null,
    aliases: ["Constellation Energy Corporation", "Constellation Energy", "Constellation En Cm"],
    tickerAliases: ["CEG"],
  },
  {
    slug: "comcast",
    name: "Comcast Corporation",
    displayName: "Comcast",
    ticker: "CMCSA",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Telecommunications",
    websiteLabel: "comcastcorporation.com",
    websiteUrl: "https://www.comcastcorporation.com",
    tradingViewSymbol: "NASDAQ:CMCSA",
    marketDataSymbol: "CMCSA",
    logoPath: null,
    aliases: ["Comcast Corporation", "Comcast", "Comcast Corp A"],
    tickerAliases: ["CMCSA"],
  },
  {
    slug: "costco",
    name: "Costco Wholesale Corporation",
    displayName: "Costco Wholesale",
    ticker: "COST",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "costco.com",
    websiteUrl: "https://www.costco.com",
    tradingViewSymbol: "NASDAQ:COST",
    marketDataSymbol: "COST",
    logoPath: null,
    aliases: ["Costco Wholesale Corporation", "Costco Wholesale"],
    tickerAliases: ["COST"],
  },
  {
    slug: "copart",
    name: "Copart, Inc.",
    displayName: "Copart",
    ticker: "CPRT",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "copart.com",
    websiteUrl: "https://www.copart.com",
    tradingViewSymbol: "NASDAQ:CPRT",
    marketDataSymbol: "CPRT",
    logoPath: null,
    aliases: ["Copart, Inc.", "Copart"],
    tickerAliases: ["CPRT"],
  },
  {
    slug: "crowdstrike",
    name: "CrowdStrike Holdings, Inc.",
    displayName: "CrowdStrike",
    ticker: "CRWD",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "crowdstrike.com",
    websiteUrl: "https://www.crowdstrike.com",
    tradingViewSymbol: "NASDAQ:CRWD",
    marketDataSymbol: "CRWD",
    logoPath: null,
    aliases: ["CrowdStrike Holdings, Inc.", "CrowdStrike", "Crowdstrike Hld Cm A"],
    tickerAliases: ["CRWD"],
  },
  {
    slug: "coreweave",
    name: "CoreWeave, Inc.",
    displayName: "CoreWeave",
    ticker: "CRWV",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "coreweave.com",
    websiteUrl: "https://www.coreweave.com",
    tradingViewSymbol: "NASDAQ:CRWV",
    marketDataSymbol: "CRWV",
    logoPath: null,
    aliases: ["CoreWeave, Inc.", "CoreWeave", "Coreweave Cl A Cs"],
    tickerAliases: ["CRWV"],
  },
  {
    slug: "cisco-systems",
    name: "Cisco Systems, Inc.",
    displayName: "Cisco Systems",
    ticker: "CSCO",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Telecommunications",
    websiteLabel: "cisco.com",
    websiteUrl: "https://www.cisco.com",
    tradingViewSymbol: "NASDAQ:CSCO",
    marketDataSymbol: "CSCO",
    logoPath: null,
    aliases: ["Cisco Systems, Inc.", "Cisco Systems", "Cisco Systems Inc."],
    tickerAliases: ["CSCO"],
  },
  {
    slug: "csx",
    name: "CSX Corporation",
    displayName: "CSX",
    ticker: "CSX",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    websiteLabel: "csx.com",
    websiteUrl: "https://www.csx.com",
    tradingViewSymbol: "NASDAQ:CSX",
    marketDataSymbol: "CSX",
    logoPath: null,
    aliases: ["CSX Corporation", "CSX"],
    tickerAliases: ["CSX"],
  },
  {
    slug: "cintas",
    name: "Cintas Corporation",
    displayName: "Cintas",
    ticker: "CTAS",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    websiteLabel: "cintas.com",
    websiteUrl: "https://www.cintas.com",
    tradingViewSymbol: "NASDAQ:CTAS",
    marketDataSymbol: "CTAS",
    logoPath: null,
    aliases: ["Cintas Corporation", "Cintas", "Cintas Corp"],
    tickerAliases: ["CTAS"],
  },
  {
    slug: "doordash",
    name: "DoorDash, Inc.",
    displayName: "DoorDash",
    ticker: "DASH",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    tradingViewSymbol: "NASDAQ:DASH",
    marketDataSymbol: "DASH",
    logoPath: null,
    aliases: ["DoorDash, Inc.", "DoorDash", "Doordash, Inc Cl A"],
    tickerAliases: ["DASH"],
  },
  {
    slug: "datadog",
    name: "Datadog, Inc.",
    displayName: "Datadog",
    ticker: "DDOG",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "datadog.com",
    websiteUrl: "https://www.datadog.com",
    tradingViewSymbol: "NASDAQ:DDOG",
    marketDataSymbol: "DDOG",
    logoPath: null,
    aliases: ["Datadog, Inc.", "Datadog", "Datadog Inc.L A Cmn"],
    tickerAliases: ["DDOG"],
  },
  {
    slug: "dexcom",
    name: "DexCom, Inc.",
    displayName: "DexCom",
    ticker: "DXCM",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Health Care",
    websiteLabel: "dexcom.com",
    websiteUrl: "https://www.dexcom.com",
    tradingViewSymbol: "NASDAQ:DXCM",
    marketDataSymbol: "DXCM",
    logoPath: null,
    aliases: ["DexCom, Inc.", "DexCom"],
    tickerAliases: ["DXCM"],
  },
  {
    slug: "exelon",
    name: "Exelon Corporation",
    displayName: "Exelon",
    ticker: "EXC",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Utilities",
    websiteLabel: "exeloncorp.com",
    websiteUrl: "https://www.exeloncorp.com",
    tradingViewSymbol: "NASDAQ:EXC",
    marketDataSymbol: "EXC",
    logoPath: null,
    aliases: ["Exelon Corporation", "Exelon", "Exelon Corp Cmn Stk"],
    tickerAliases: ["EXC"],
  },
  {
    slug: "diamondback-energy",
    name: "Diamondback Energy, Inc.",
    displayName: "Diamondback Energy",
    ticker: "FANG",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Energy",
    websiteLabel: "diamondbackenergy.com",
    websiteUrl: "https://www.diamondbackenergy.com",
    tradingViewSymbol: "NASDAQ:FANG",
    marketDataSymbol: "FANG",
    logoPath: null,
    aliases: ["Diamondback Energy, Inc.", "Diamondback Energy"],
    tickerAliases: ["FANG"],
  },
  {
    slug: "fastenal",
    name: "Fastenal Company",
    displayName: "Fastenal",
    ticker: "FAST",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "fastenal.com",
    websiteUrl: "https://www.fastenal.com",
    tradingViewSymbol: "NASDAQ:FAST",
    marketDataSymbol: "FAST",
    logoPath: null,
    aliases: ["Fastenal Company", "Fastenal", "Fastenal Co"],
    tickerAliases: ["FAST"],
  },
  {
    slug: "ferrovial",
    name: "Ferrovial N.V.",
    displayName: "Ferrovial",
    ticker: "FER",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    websiteLabel: "ferrovial.com",
    websiteUrl: "https://www.ferrovial.com",
    tradingViewSymbol: "NASDAQ:FER",
    marketDataSymbol: "FER",
    logoPath: null,
    aliases: ["Ferrovial N.V.", "Ferrovial", "Ferrovial N.V. Os"],
    tickerAliases: ["FER"],
  },
  {
    slug: "fortinet",
    name: "Fortinet, Inc.",
    displayName: "Fortinet",
    ticker: "FTNT",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "fortinet.com",
    websiteUrl: "https://www.fortinet.com",
    tradingViewSymbol: "NASDAQ:FTNT",
    marketDataSymbol: "FTNT",
    logoPath: null,
    aliases: ["Fortinet, Inc.", "Fortinet"],
    tickerAliases: ["FTNT"],
  },
  {
    slug: "ge-healthcare-technologies",
    name: "GE HealthCare Technologies Inc.",
    displayName: "GE HealthCare Technologies",
    ticker: "GEHC",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Health Care",
    websiteLabel: "gehealthcare.com",
    websiteUrl: "https://www.gehealthcare.com",
    tradingViewSymbol: "NASDAQ:GEHC",
    marketDataSymbol: "GEHC",
    logoPath: null,
    aliases: ["GE HealthCare Technologies Inc.", "GE HealthCare Technologies", "Ge Healthcare Cm"],
    tickerAliases: ["GEHC"],
  },
  {
    slug: "gilead-sciences",
    name: "Gilead Sciences, Inc.",
    displayName: "Gilead Sciences",
    ticker: "GILD",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Health Care",
    websiteLabel: "gilead.com",
    websiteUrl: "https://www.gilead.com",
    tradingViewSymbol: "NASDAQ:GILD",
    marketDataSymbol: "GILD",
    logoPath: null,
    aliases: ["Gilead Sciences, Inc.", "Gilead Sciences", "Gilead Sciences, Inc"],
    tickerAliases: ["GILD"],
  },
  {
    slug: "alphabet",
    name: "Alphabet Inc.",
    displayName: "Alphabet",
    ticker: "GOOGL",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "abc.xyz",
    websiteUrl: "https://www.abc.xyz",
    tradingViewSymbol: "NASDAQ:GOOGL",
    marketDataSymbol: "GOOGL",
    logoPath: null,
    aliases: ["Alphabet", "Alphabet Inc.", "Google"],
    tickerAliases: ["GOOGL", "GOOG"],
  },
  {
    slug: "honeywell-international",
    name: "Honeywell International Inc.",
    displayName: "Honeywell International",
    ticker: "HON",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    websiteLabel: "honeywell.com",
    websiteUrl: "https://www.honeywell.com",
    tradingViewSymbol: "NASDAQ:HON",
    marketDataSymbol: "HON",
    logoPath: null,
    aliases: ["Honeywell International Inc.", "Honeywell International", "Honeywell Intl Inc"],
    tickerAliases: ["HON"],
  },
  {
    slug: "honeywell-aerospace",
    name: "Honeywell Aerospace Inc.",
    displayName: "Honeywell Aerospace",
    ticker: "HONA",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    tradingViewSymbol: "NASDAQ:HONA",
    marketDataSymbol: "HONA",
    logoPath: null,
    aliases: ["Honeywell Aerospace Inc.", "Honeywell Aerospace", "Hnywll Aerospace"],
    tickerAliases: ["HONA"],
  },
  {
    slug: "idexx-laboratories",
    name: "IDEXX Laboratories, Inc.",
    displayName: "IDEXX Laboratories",
    ticker: "IDXX",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Health Care",
    websiteLabel: "idexx.com",
    websiteUrl: "https://www.idexx.com",
    tradingViewSymbol: "NASDAQ:IDXX",
    marketDataSymbol: "IDXX",
    logoPath: null,
    aliases: ["IDEXX Laboratories, Inc.", "IDEXX Laboratories"],
    tickerAliases: ["IDXX"],
  },
  {
    slug: "intel",
    name: "Intel Corporation",
    displayName: "Intel",
    ticker: "INTC",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "intel.com",
    websiteUrl: "https://www.intel.com",
    tradingViewSymbol: "NASDAQ:INTC",
    marketDataSymbol: "INTC",
    logoPath: null,
    aliases: ["Intel Corporation", "Intel", "Intel Corp"],
    tickerAliases: ["INTC"],
  },
  {
    slug: "intuit",
    name: "Intuit Inc.",
    displayName: "Intuit",
    ticker: "INTU",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "intuit.com",
    websiteUrl: "https://www.intuit.com",
    tradingViewSymbol: "NASDAQ:INTU",
    marketDataSymbol: "INTU",
    logoPath: null,
    aliases: ["Intuit Inc.", "Intuit", "Intuit Inc"],
    tickerAliases: ["INTU"],
  },
  {
    slug: "intuitive-surgical",
    name: "Intuitive Surgical, Inc.",
    displayName: "Intuitive Surgical",
    ticker: "ISRG",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Health Care",
    websiteLabel: "intuitive.com",
    websiteUrl: "https://www.intuitive.com",
    tradingViewSymbol: "NASDAQ:ISRG",
    marketDataSymbol: "ISRG",
    logoPath: null,
    aliases: ["Intuitive Surgical, Inc.", "Intuitive Surgical", "Intuitive Surg, Inc."],
    tickerAliases: ["ISRG"],
  },
  {
    slug: "keurig-dr-pepper",
    name: "Keurig Dr Pepper Inc.",
    displayName: "Keurig Dr Pepper",
    ticker: "KDP",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Staples",
    websiteLabel: "keurigdrpepper.com",
    websiteUrl: "https://www.keurigdrpepper.com",
    tradingViewSymbol: "NASDAQ:KDP",
    marketDataSymbol: "KDP",
    logoPath: null,
    aliases: ["Keurig Dr Pepper Inc.", "Keurig Dr Pepper", "Keurig Dr Pepper Inc"],
    tickerAliases: ["KDP"],
  },
  {
    slug: "kla",
    name: "KLA Corporation ",
    displayName: "KLA",
    ticker: "KLAC",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "kla.com",
    websiteUrl: "https://www.kla.com",
    tradingViewSymbol: "NASDAQ:KLAC",
    marketDataSymbol: "KLAC",
    logoPath: null,
    aliases: ["KLA Corporation ", "KLA", "Kla Cp Cmn Stk"],
    tickerAliases: ["KLAC"],
  },
  {
    slug: "linde",
    name: "Linde plc",
    displayName: "Linde",
    ticker: "LIN",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Basic Materials",
    websiteLabel: "linde.com",
    websiteUrl: "https://www.linde.com",
    tradingViewSymbol: "NASDAQ:LIN",
    marketDataSymbol: "LIN",
    logoPath: null,
    aliases: ["Linde plc", "Linde"],
    tickerAliases: ["LIN"],
  },
  {
    slug: "lumentum",
    name: "Lumentum Holdings Inc.",
    displayName: "Lumentum",
    ticker: "LITE",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Telecommunications",
    websiteLabel: "lumentum.com",
    websiteUrl: "https://www.lumentum.com",
    tradingViewSymbol: "NASDAQ:LITE",
    marketDataSymbol: "LITE",
    logoPath: null,
    aliases: ["Lumentum Holdings Inc.", "Lumentum", "Lumentum Hld Cm"],
    tickerAliases: ["LITE"],
  },
  {
    slug: "lam-research",
    name: "Lam Research Corporation",
    displayName: "Lam Research",
    ticker: "LRCX",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "lamresearch.com",
    websiteUrl: "https://www.lamresearch.com",
    tradingViewSymbol: "NASDAQ:LRCX",
    marketDataSymbol: "LRCX",
    logoPath: null,
    aliases: ["Lam Research Corporation", "Lam Research", "Lam Research Corp"],
    tickerAliases: ["LRCX"],
  },
  {
    slug: "marriott-international",
    name: "Marriott International",
    displayName: "Marriott International",
    ticker: "MAR",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "marriott.com",
    websiteUrl: "https://www.marriott.com",
    tradingViewSymbol: "NASDAQ:MAR",
    marketDataSymbol: "MAR",
    logoPath: null,
    aliases: ["Marriott International", "Marriott Int Cl A Cm"],
    tickerAliases: ["MAR"],
  },
  {
    slug: "microchip-technology",
    name: "Microchip Technology Incorporated",
    displayName: "Microchip Technology",
    ticker: "MCHP",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "microchip.com",
    websiteUrl: "https://www.microchip.com",
    tradingViewSymbol: "NASDAQ:MCHP",
    marketDataSymbol: "MCHP",
    logoPath: null,
    aliases: ["Microchip Technology Incorporated", "Microchip Technology"],
    tickerAliases: ["MCHP"],
  },
  {
    slug: "mondelez-international",
    name: "Mondelez International, Inc.",
    displayName: "Mondelez International",
    ticker: "MDLZ",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Staples",
    websiteLabel: "mondelezinternational.com",
    websiteUrl: "https://www.mondelezinternational.com",
    tradingViewSymbol: "NASDAQ:MDLZ",
    marketDataSymbol: "MDLZ",
    logoPath: null,
    aliases: ["Mondelez International, Inc.", "Mondelez International", "Mondelez Intl Cmn A"],
    tickerAliases: ["MDLZ"],
  },
  {
    slug: "mercadolibre",
    name: "MercadoLibre, Inc.",
    displayName: "MercadoLibre",
    ticker: "MELI",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "mercadolibre.com",
    websiteUrl: "https://www.mercadolibre.com",
    tradingViewSymbol: "NASDAQ:MELI",
    marketDataSymbol: "MELI",
    logoPath: null,
    aliases: ["MercadoLibre, Inc.", "MercadoLibre"],
    tickerAliases: ["MELI"],
  },
  {
    slug: "meta-platforms",
    name: "Meta Platforms, Inc.",
    displayName: "Meta Platforms",
    ticker: "META",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "about.meta.com",
    websiteUrl: "https://about.meta.com",
    tradingViewSymbol: "NASDAQ:META",
    marketDataSymbol: "META",
    logoPath: null,
    aliases: ["Meta Platforms, Inc.", "Meta Platforms"],
    tickerAliases: ["META"],
  },
  {
    slug: "monster-beverage",
    name: "Monster Beverage Corporation",
    displayName: "Monster Beverage",
    ticker: "MNST",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Staples",
    websiteLabel: "monsterbevcorp.com",
    websiteUrl: "https://www.monsterbevcorp.com",
    tradingViewSymbol: "NASDAQ:MNST",
    marketDataSymbol: "MNST",
    logoPath: null,
    aliases: ["Monster Beverage Corporation", "Monster Beverage", "Monster Beverage Cp"],
    tickerAliases: ["MNST"],
  },
  {
    slug: "monolithic-power-systems",
    name: "Monolithic Power Systems, Inc.",
    displayName: "Monolithic Power Systems",
    ticker: "MPWR",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "monolithicpower.com",
    websiteUrl: "https://www.monolithicpower.com",
    tradingViewSymbol: "NASDAQ:MPWR",
    marketDataSymbol: "MPWR",
    logoPath: null,
    aliases: ["Monolithic Power Systems, Inc.", "Monolithic Power Systems", "Monolithic Power Sys"],
    tickerAliases: ["MPWR"],
  },
  {
    slug: "marvell-technology",
    name: "Marvell Technology, Inc.",
    displayName: "Marvell Technology",
    ticker: "MRVL",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "marvell.com",
    websiteUrl: "https://www.marvell.com",
    tradingViewSymbol: "NASDAQ:MRVL",
    marketDataSymbol: "MRVL",
    logoPath: null,
    aliases: ["Marvell Technology, Inc.", "Marvell Technology", "Marvell Tech Inc Cmn"],
    tickerAliases: ["MRVL"],
  },
  {
    slug: "microsoft",
    name: "Microsoft Corporation",
    displayName: "Microsoft",
    ticker: "MSFT",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "microsoft.com",
    websiteUrl: "https://www.microsoft.com",
    tradingViewSymbol: "NASDAQ:MSFT",
    marketDataSymbol: "MSFT",
    logoPath: null,
    aliases: ["Microsoft Corporation", "Microsoft", "Microsoft Corp"],
    tickerAliases: ["MSFT"],
  },
  {
    slug: "strategy-inc",
    name: "Strategy Inc",
    displayName: "Strategy",
    ticker: "MSTR",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "strategy.com",
    websiteUrl: "https://www.strategy.com",
    tradingViewSymbol: "NASDAQ:MSTR",
    marketDataSymbol: "MSTR",
    logoPath: null,
    aliases: ["Strategy Inc", "Strategy", "Strategy Inc Cl A Cs"],
    tickerAliases: ["MSTR"],
  },
  {
    slug: "micron-technology",
    name: "Micron Technology, Inc.",
    displayName: "Micron Technology",
    ticker: "MU",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "micron.com",
    websiteUrl: "https://www.micron.com",
    tradingViewSymbol: "NASDAQ:MU",
    marketDataSymbol: "MU",
    logoPath: null,
    aliases: ["Micron Technology, Inc.", "Micron Technology"],
    tickerAliases: ["MU"],
  },
  {
    slug: "nebius",
    name: "Nebius Group N.V.",
    displayName: "Nebius",
    ticker: "NBIS",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "group.nebius.com",
    websiteUrl: "https://www.group.nebius.com",
    tradingViewSymbol: "NASDAQ:NBIS",
    marketDataSymbol: "NBIS",
    logoPath: null,
    aliases: ["Nebius Group N.V.", "Nebius", "Nebius Grp Nv Ord A"],
    tickerAliases: ["NBIS"],
  },
  {
    slug: "netflix",
    name: "Netflix, Inc.",
    displayName: "Netflix",
    ticker: "NFLX",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "netflix.com",
    websiteUrl: "https://www.netflix.com",
    tradingViewSymbol: "NASDAQ:NFLX",
    marketDataSymbol: "NFLX",
    logoPath: null,
    aliases: ["Netflix, Inc.", "Netflix"],
    tickerAliases: ["NFLX"],
  },
  {
    slug: "nvidia",
    name: "NVIDIA Corporation",
    displayName: "NVIDIA",
    ticker: "NVDA",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "nvidia.com",
    websiteUrl: "https://www.nvidia.com",
    tradingViewSymbol: "NASDAQ:NVDA",
    marketDataSymbol: "NVDA",
    logoPath: null,
    aliases: ["NVIDIA Corporation", "NVIDIA"],
    tickerAliases: ["NVDA"],
  },
  {
    slug: "nxp-semiconductors",
    name: "NXP Semiconductors N.V.",
    displayName: "NXP Semiconductors",
    ticker: "NXPI",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "nxp.com",
    websiteUrl: "https://www.nxp.com",
    tradingViewSymbol: "NASDAQ:NXPI",
    marketDataSymbol: "NXPI",
    logoPath: null,
    aliases: ["NXP Semiconductors N.V.", "NXP Semiconductors"],
    tickerAliases: ["NXPI"],
  },
  {
    slug: "old-dominion-freight-line",
    name: "Old Dominion Freight Line, Inc.",
    displayName: "Old Dominion Freight Line",
    ticker: "ODFL",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    websiteLabel: "odfl.com",
    websiteUrl: "https://www.odfl.com",
    tradingViewSymbol: "NASDAQ:ODFL",
    marketDataSymbol: "ODFL",
    logoPath: null,
    aliases: ["Old Dominion Freight Line, Inc.", "Old Dominion Freight Line", "Old Dominion Freig"],
    tickerAliases: ["ODFL"],
  },
  {
    slug: "oreilly-automotive",
    name: "O'Reilly Automotive, Inc.",
    displayName: "O'Reilly Automotive",
    ticker: "ORLY",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "oreillyauto.com",
    websiteUrl: "https://www.oreillyauto.com",
    tradingViewSymbol: "NASDAQ:ORLY",
    marketDataSymbol: "ORLY",
    logoPath: null,
    aliases: ["O'Reilly Automotive, Inc.", "O'Reilly Automotive"],
    tickerAliases: ["ORLY"],
  },
  {
    slug: "palo-alto-networks",
    name: "Palo Alto Networks, Inc.",
    displayName: "Palo Alto Networks",
    ticker: "PANW",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "paloaltonetworks.com",
    websiteUrl: "https://www.paloaltonetworks.com",
    tradingViewSymbol: "NASDAQ:PANW",
    marketDataSymbol: "PANW",
    logoPath: null,
    aliases: ["Palo Alto Networks, Inc.", "Palo Alto Networks", "Palo Alto Ntwks Cm"],
    tickerAliases: ["PANW"],
  },
  {
    slug: "paychex",
    name: "Paychex, Inc.",
    displayName: "Paychex",
    ticker: "PAYX",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    websiteLabel: "paychex.com",
    websiteUrl: "https://www.paychex.com",
    tradingViewSymbol: "NASDAQ:PAYX",
    marketDataSymbol: "PAYX",
    logoPath: null,
    aliases: ["Paychex, Inc.", "Paychex"],
    tickerAliases: ["PAYX"],
  },
  {
    slug: "paccar",
    name: "PACCAR Inc.",
    displayName: "PACCAR",
    ticker: "PCAR",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    websiteLabel: "paccar.com",
    websiteUrl: "https://www.paccar.com",
    tradingViewSymbol: "NASDAQ:PCAR",
    marketDataSymbol: "PCAR",
    logoPath: null,
    aliases: ["PACCAR Inc.", "PACCAR"],
    tickerAliases: ["PCAR"],
  },
  {
    slug: "pdd-holdings",
    name: "PDD Holdings Inc.",
    displayName: "PDD",
    ticker: "PDD",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "pddholdings.com",
    websiteUrl: "https://www.pddholdings.com",
    tradingViewSymbol: "NASDAQ:PDD",
    marketDataSymbol: "PDD",
    logoPath: null,
    aliases: ["PDD Holdings Inc.", "PDD", "Pdd Holdings Inc Ads"],
    tickerAliases: ["PDD"],
  },
  {
    slug: "pepsico",
    name: "PepsiCo, Inc.",
    displayName: "PepsiCo",
    ticker: "PEP",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Staples",
    websiteLabel: "pepsico.com",
    websiteUrl: "https://www.pepsico.com",
    tradingViewSymbol: "NASDAQ:PEP",
    marketDataSymbol: "PEP",
    logoPath: null,
    aliases: ["PepsiCo, Inc.", "PepsiCo", "Pepsico Inc"],
    tickerAliases: ["PEP"],
  },
  {
    slug: "palantir-technologies",
    name: "Palantir Technologies Inc.",
    displayName: "Palantir Technologies",
    ticker: "PLTR",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "palantir.com",
    websiteUrl: "https://www.palantir.com",
    tradingViewSymbol: "NASDAQ:PLTR",
    marketDataSymbol: "PLTR",
    logoPath: null,
    aliases: ["Palantir Technologies Inc.", "Palantir Technologies", "Palantir Tech Cl A"],
    tickerAliases: ["PLTR"],
  },
  {
    slug: "paypal",
    name: "PayPal Holdings, Inc.",
    displayName: "PayPal",
    ticker: "PYPL",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    websiteLabel: "paypal.com",
    websiteUrl: "https://www.paypal.com",
    tradingViewSymbol: "NASDAQ:PYPL",
    marketDataSymbol: "PYPL",
    logoPath: null,
    aliases: ["PayPal Holdings, Inc.", "PayPal", "Paypal Holdings"],
    tickerAliases: ["PYPL"],
  },
  {
    slug: "qualcomm",
    name: "QUALCOMM Incorporated",
    displayName: "QUALCOMM",
    ticker: "QCOM",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "qualcomm.com",
    websiteUrl: "https://www.qualcomm.com",
    tradingViewSymbol: "NASDAQ:QCOM",
    marketDataSymbol: "QCOM",
    logoPath: null,
    aliases: ["QUALCOMM Incorporated", "QUALCOMM", "Qualcomm Inc"],
    tickerAliases: ["QCOM"],
  },
  {
    slug: "regeneron-pharmaceuticals",
    name: "Regeneron Pharmaceuticals, Inc.",
    displayName: "Regeneron Pharmaceuticals",
    ticker: "REGN",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Health Care",
    websiteLabel: "regeneron.com",
    websiteUrl: "https://www.regeneron.com",
    tradingViewSymbol: "NASDAQ:REGN",
    marketDataSymbol: "REGN",
    logoPath: null,
    aliases: ["Regeneron Pharmaceuticals, Inc.", "Regeneron Pharmaceuticals", "Regeneron Pharmaceut"],
    tickerAliases: ["REGN"],
  },
  {
    slug: "rocket-lab",
    name: "Rocket Lab Corporation",
    displayName: "Rocket Lab",
    ticker: "RKLB",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    websiteLabel: "rocketlabusa.com",
    websiteUrl: "https://www.rocketlabusa.com",
    tradingViewSymbol: "NASDAQ:RKLB",
    marketDataSymbol: "RKLB",
    logoPath: null,
    aliases: ["Rocket Lab Corporation", "Rocket Lab", "Rocket Lab Corp Cmn"],
    tickerAliases: ["RKLB"],
  },
  {
    slug: "roper-technologies",
    name: "Roper Technologies, Inc.",
    displayName: "Roper Technologies",
    ticker: "ROP",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    websiteLabel: "ropertech.com",
    websiteUrl: "https://www.ropertech.com",
    tradingViewSymbol: "NASDAQ:ROP",
    marketDataSymbol: "ROP",
    logoPath: null,
    aliases: ["Roper Technologies, Inc.", "Roper Technologies", "Roper Tech Cmn"],
    tickerAliases: ["ROP"],
  },
  {
    slug: "ross-stores",
    name: "Ross Stores, Inc.",
    displayName: "Ross Stores",
    ticker: "ROST",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "rossstores.com",
    websiteUrl: "https://www.rossstores.com",
    tradingViewSymbol: "NASDAQ:ROST",
    marketDataSymbol: "ROST",
    logoPath: null,
    aliases: ["Ross Stores, Inc.", "Ross Stores"],
    tickerAliases: ["ROST"],
  },
  {
    slug: "starbucks",
    name: "Starbucks Corporation",
    displayName: "Starbucks",
    ticker: "SBUX",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "starbucks.com",
    websiteUrl: "https://www.starbucks.com",
    tradingViewSymbol: "NASDAQ:SBUX",
    marketDataSymbol: "SBUX",
    logoPath: null,
    aliases: ["Starbucks Corporation", "Starbucks", "Starbucks Corp"],
    tickerAliases: ["SBUX"],
  },
  {
    slug: "shopify",
    name: "Shopify Inc.",
    displayName: "Shopify",
    ticker: "SHOP",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "shopify.com",
    websiteUrl: "https://www.shopify.com",
    tradingViewSymbol: "NASDAQ:SHOP",
    marketDataSymbol: "SHOP",
    logoPath: null,
    aliases: ["Shopify Inc.", "Shopify"],
    tickerAliases: ["SHOP"],
  },
  {
    slug: "sandisk",
    name: "Sandisk Corporation",
    displayName: "Sandisk",
    ticker: "SNDK",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "sandisk.com",
    websiteUrl: "https://www.sandisk.com",
    tradingViewSymbol: "NASDAQ:SNDK",
    marketDataSymbol: "SNDK",
    logoPath: null,
    aliases: ["Sandisk Corporation", "Sandisk", "Sandisk Cp Cmn"],
    tickerAliases: ["SNDK"],
  },
  {
    slug: "synopsys",
    name: "Synopsys, Inc.",
    displayName: "Synopsys",
    ticker: "SNPS",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "synopsys.com",
    websiteUrl: "https://www.synopsys.com",
    tradingViewSymbol: "NASDAQ:SNPS",
    marketDataSymbol: "SNPS",
    logoPath: null,
    aliases: ["Synopsys, Inc.", "Synopsys"],
    tickerAliases: ["SNPS"],
  },
  {
    slug: "space-exploration-technologies",
    name: "Space Exploration Technologies Corp.",
    displayName: "Space Exploration Technologies",
    ticker: "SPCX",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "spacex.com  ",
    websiteUrl: "https://www.spacex.com  ",
    tradingViewSymbol: "NASDAQ:SPCX",
    marketDataSymbol: "SPCX",
    logoPath: null,
    aliases: ["Space Exploration Technologies Corp.", "Space Exploration Technologies", "Space Expl Tch Cmn A"],
    tickerAliases: ["SPCX"],
  },
  {
    slug: "seagate-technology",
    name: "Seagate Technology Holdings PLC",
    displayName: "Seagate Technology",
    ticker: "STX",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "seagate.com",
    websiteUrl: "https://www.seagate.com",
    tradingViewSymbol: "NASDAQ:STX",
    marketDataSymbol: "STX",
    logoPath: null,
    aliases: ["Seagate Technology Holdings PLC", "Seagate Technology", "Seagate Tch Hldgs Or"],
    tickerAliases: ["STX"],
  },
  {
    slug: "teradyne",
    name: "Teradyne, Inc.",
    displayName: "Teradyne",
    ticker: "TER",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    websiteLabel: "teradyne.com",
    websiteUrl: "https://www.teradyne.com",
    tradingViewSymbol: "NASDAQ:TER",
    marketDataSymbol: "TER",
    logoPath: null,
    aliases: ["Teradyne, Inc.", "Teradyne", "Teradyne Inc Cmn"],
    tickerAliases: ["TER"],
  },
  {
    slug: "t-mobile-us",
    name: "T-Mobile US, Inc.",
    displayName: "T-Mobile US",
    ticker: "TMUS",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Telecommunications",
    websiteLabel: "t-mobile.com",
    websiteUrl: "https://www.t-mobile.com",
    tradingViewSymbol: "NASDAQ:TMUS",
    marketDataSymbol: "TMUS",
    logoPath: null,
    aliases: ["T-Mobile US, Inc.", "T-Mobile US", "T-Mobile Us Cmn"],
    tickerAliases: ["TMUS"],
  },
  {
    slug: "thomson-reuters",
    name: "Thomson Reuters Corp",
    displayName: "Thomson Reuters",
    ticker: "TRI",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "thomsonreuters.com",
    websiteUrl: "https://www.thomsonreuters.com",
    tradingViewSymbol: "NASDAQ:TRI",
    marketDataSymbol: "TRI",
    logoPath: null,
    aliases: ["Thomson Reuters Corp", "Thomson Reuters", "Thomson Reuters Cmn"],
    tickerAliases: ["TRI"],
  },
  {
    slug: "tesla",
    name: "Tesla, Inc. ",
    displayName: "Tesla",
    ticker: "TSLA",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Industrials",
    websiteLabel: "tesla.com",
    websiteUrl: "https://www.tesla.com",
    tradingViewSymbol: "NASDAQ:TSLA",
    marketDataSymbol: "TSLA",
    logoPath: null,
    aliases: ["Tesla, Inc. ", "Tesla", "Tesla, Inc."],
    tickerAliases: ["TSLA"],
  },
  {
    slug: "take-two-interactive-software",
    name: "Take-Two Interactive Software, Inc.",
    displayName: "Take-Two Interactive Software",
    ticker: "TTWO",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "take2games.com",
    websiteUrl: "https://www.take2games.com",
    tradingViewSymbol: "NASDAQ:TTWO",
    marketDataSymbol: "TTWO",
    logoPath: null,
    aliases: ["Take-Two Interactive Software, Inc.", "Take-Two Interactive Software", "Take-Two Interacti"],
    tickerAliases: ["TTWO"],
  },
  {
    slug: "texas-instruments",
    name: "Texas Instruments Incorporated",
    displayName: "Texas Instruments",
    ticker: "TXN",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "ti.com",
    websiteUrl: "https://www.ti.com",
    tradingViewSymbol: "NASDAQ:TXN",
    marketDataSymbol: "TXN",
    logoPath: null,
    aliases: ["Texas Instruments Incorporated", "Texas Instruments"],
    tickerAliases: ["TXN"],
  },
  {
    slug: "vertex-pharmaceuticals",
    name: "Vertex Pharmaceuticals Incorporated",
    displayName: "Vertex Pharmaceuticals",
    ticker: "VRTX",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Health Care",
    websiteLabel: "vrtx.com",
    websiteUrl: "https://www.vrtx.com",
    tradingViewSymbol: "NASDAQ:VRTX",
    marketDataSymbol: "VRTX",
    logoPath: null,
    aliases: ["Vertex Pharmaceuticals Incorporated", "Vertex Pharmaceuticals", "Vertex Pharmaceutic"],
    tickerAliases: ["VRTX"],
  },
  {
    slug: "warner-bros-discovery",
    name: "Warner Bros. Discovery, Inc.",
    displayName: "Warner Bros. Discovery",
    ticker: "WBD",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Telecommunications",
    websiteLabel: "wbd.com",
    websiteUrl: "https://www.wbd.com",
    tradingViewSymbol: "NASDAQ:WBD",
    marketDataSymbol: "WBD",
    logoPath: null,
    aliases: ["Warner Bros. Discovery, Inc.", "Warner Bros. Discovery", "Wrnr Brs Ds Cm Wi"],
    tickerAliases: ["WBD"],
  },
  {
    slug: "workday",
    name: "Workday, Inc.",
    displayName: "Workday",
    ticker: "WDAY",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "workday.com",
    websiteUrl: "https://www.workday.com",
    tradingViewSymbol: "NASDAQ:WDAY",
    marketDataSymbol: "WDAY",
    logoPath: null,
    aliases: ["Workday, Inc.", "Workday", "Workday Inc Cl A"],
    tickerAliases: ["WDAY"],
  },
  {
    slug: "western-digital",
    name: "Western Digital Corporation",
    displayName: "Western Digital",
    ticker: "WDC",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Technology",
    websiteLabel: "westerndigital.com",
    websiteUrl: "https://www.westerndigital.com",
    tradingViewSymbol: "NASDAQ:WDC",
    marketDataSymbol: "WDC",
    logoPath: null,
    aliases: ["Western Digital Corporation", "Western Digital", "Western Digital Cp"],
    tickerAliases: ["WDC"],
  },
  {
    slug: "walmart",
    name: "Walmart Inc.",
    displayName: "Walmart",
    ticker: "WMT",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Consumer Discretionary",
    websiteLabel: "stock.walmart.com",
    websiteUrl: "https://stock.walmart.com",
    tradingViewSymbol: "NASDAQ:WMT",
    marketDataSymbol: "WMT",
    logoPath: null,
    aliases: ["Walmart Inc.", "Walmart", "Walmart Inc Cmn"],
    tickerAliases: ["WMT"],
  },
  {
    slug: "xcel-energy",
    name: "Xcel Energy Inc.",
    displayName: "Xcel Energy",
    ticker: "XEL",
    exchange: "Nasdaq",
    countryCode: "US",
    countryName: "USA",
    sector: "Utilities",
    websiteLabel: "xcelenergy.com",
    websiteUrl: "https://www.xcelenergy.com",
    tradingViewSymbol: "NASDAQ:XEL",
    marketDataSymbol: "XEL",
    logoPath: null,
    aliases: ["Xcel Energy Inc.", "Xcel Energy", "Xcel Energy Cmn"],
    tickerAliases: ["XEL"],
  },
] as const satisfies readonly CompanyProfile[];

export const NASDAQ100_SECURITIES = [
  { symbol: "AAPL", issuerSlug: "apple" },
  { symbol: "ABNB", issuerSlug: "airbnb" },
  { symbol: "ADBE", issuerSlug: "adobe" },
  { symbol: "ADI", issuerSlug: "analog-devices" },
  { symbol: "ADP", issuerSlug: "automatic-data-processing" },
  { symbol: "ADSK", issuerSlug: "autodesk" },
  { symbol: "AEP", issuerSlug: "american-electric-power" },
  { symbol: "ALAB", issuerSlug: "astera-labs" },
  { symbol: "ALNY", issuerSlug: "alnylam-pharmaceuticals" },
  { symbol: "AMAT", issuerSlug: "applied-materials" },
  { symbol: "AMD", issuerSlug: "advanced-micro-devices" },
  { symbol: "AMGN", issuerSlug: "amgen" },
  { symbol: "AMZN", issuerSlug: "amazon" },
  { symbol: "APP", issuerSlug: "applovin" },
  { symbol: "ARM", issuerSlug: "arm" },
  { symbol: "ASML", issuerSlug: "asml" },
  { symbol: "AVGO", issuerSlug: "broadcom" },
  { symbol: "AXON", issuerSlug: "axon-enterprise" },
  { symbol: "BKNG", issuerSlug: "booking-holdings" },
  { symbol: "BKR", issuerSlug: "baker-hughes" },
  { symbol: "CCEP", issuerSlug: "coca-cola-europacific-partners" },
  { symbol: "CDNS", issuerSlug: "cadence-design-systems" },
  { symbol: "CEG", issuerSlug: "constellation-energy" },
  { symbol: "CMCSA", issuerSlug: "comcast" },
  { symbol: "COST", issuerSlug: "costco" },
  { symbol: "CPRT", issuerSlug: "copart" },
  { symbol: "CRWD", issuerSlug: "crowdstrike" },
  { symbol: "CRWV", issuerSlug: "coreweave" },
  { symbol: "CSCO", issuerSlug: "cisco-systems" },
  { symbol: "CSX", issuerSlug: "csx" },
  { symbol: "CTAS", issuerSlug: "cintas" },
  { symbol: "DASH", issuerSlug: "doordash" },
  { symbol: "DDOG", issuerSlug: "datadog" },
  { symbol: "DXCM", issuerSlug: "dexcom" },
  { symbol: "EXC", issuerSlug: "exelon" },
  { symbol: "FANG", issuerSlug: "diamondback-energy" },
  { symbol: "FAST", issuerSlug: "fastenal" },
  { symbol: "FER", issuerSlug: "ferrovial" },
  { symbol: "FTNT", issuerSlug: "fortinet" },
  { symbol: "GEHC", issuerSlug: "ge-healthcare-technologies" },
  { symbol: "GILD", issuerSlug: "gilead-sciences" },
  { symbol: "GOOG", issuerSlug: "alphabet" },
  { symbol: "GOOGL", issuerSlug: "alphabet" },
  { symbol: "HON", issuerSlug: "honeywell-international" },
  { symbol: "HONA", issuerSlug: "honeywell-aerospace" },
  { symbol: "IDXX", issuerSlug: "idexx-laboratories" },
  { symbol: "INTC", issuerSlug: "intel" },
  { symbol: "INTU", issuerSlug: "intuit" },
  { symbol: "ISRG", issuerSlug: "intuitive-surgical" },
  { symbol: "KDP", issuerSlug: "keurig-dr-pepper" },
  { symbol: "KLAC", issuerSlug: "kla" },
  { symbol: "LIN", issuerSlug: "linde" },
  { symbol: "LITE", issuerSlug: "lumentum" },
  { symbol: "LRCX", issuerSlug: "lam-research" },
  { symbol: "MAR", issuerSlug: "marriott-international" },
  { symbol: "MCHP", issuerSlug: "microchip-technology" },
  { symbol: "MDLZ", issuerSlug: "mondelez-international" },
  { symbol: "MELI", issuerSlug: "mercadolibre" },
  { symbol: "META", issuerSlug: "meta-platforms" },
  { symbol: "MNST", issuerSlug: "monster-beverage" },
  { symbol: "MPWR", issuerSlug: "monolithic-power-systems" },
  { symbol: "MRVL", issuerSlug: "marvell-technology" },
  { symbol: "MSFT", issuerSlug: "microsoft" },
  { symbol: "MSTR", issuerSlug: "strategy-inc" },
  { symbol: "MU", issuerSlug: "micron-technology" },
  { symbol: "NBIS", issuerSlug: "nebius" },
  { symbol: "NFLX", issuerSlug: "netflix" },
  { symbol: "NVDA", issuerSlug: "nvidia" },
  { symbol: "NXPI", issuerSlug: "nxp-semiconductors" },
  { symbol: "ODFL", issuerSlug: "old-dominion-freight-line" },
  { symbol: "ORLY", issuerSlug: "oreilly-automotive" },
  { symbol: "PANW", issuerSlug: "palo-alto-networks" },
  { symbol: "PAYX", issuerSlug: "paychex" },
  { symbol: "PCAR", issuerSlug: "paccar" },
  { symbol: "PDD", issuerSlug: "pdd-holdings" },
  { symbol: "PEP", issuerSlug: "pepsico" },
  { symbol: "PLTR", issuerSlug: "palantir-technologies" },
  { symbol: "PYPL", issuerSlug: "paypal" },
  { symbol: "QCOM", issuerSlug: "qualcomm" },
  { symbol: "REGN", issuerSlug: "regeneron-pharmaceuticals" },
  { symbol: "RKLB", issuerSlug: "rocket-lab" },
  { symbol: "ROP", issuerSlug: "roper-technologies" },
  { symbol: "ROST", issuerSlug: "ross-stores" },
  { symbol: "SBUX", issuerSlug: "starbucks" },
  { symbol: "SHOP", issuerSlug: "shopify" },
  { symbol: "SNDK", issuerSlug: "sandisk" },
  { symbol: "SNPS", issuerSlug: "synopsys" },
  { symbol: "SPCX", issuerSlug: "space-exploration-technologies" },
  { symbol: "STX", issuerSlug: "seagate-technology" },
  { symbol: "TER", issuerSlug: "teradyne" },
  { symbol: "TMUS", issuerSlug: "t-mobile-us" },
  { symbol: "TRI", issuerSlug: "thomson-reuters" },
  { symbol: "TSLA", issuerSlug: "tesla" },
  { symbol: "TTWO", issuerSlug: "take-two-interactive-software" },
  { symbol: "TXN", issuerSlug: "texas-instruments" },
  { symbol: "VRTX", issuerSlug: "vertex-pharmaceuticals" },
  { symbol: "WBD", issuerSlug: "warner-bros-discovery" },
  { symbol: "WDAY", issuerSlug: "workday" },
  { symbol: "WDC", issuerSlug: "western-digital" },
  { symbol: "WMT", issuerSlug: "walmart" },
  { symbol: "XEL", issuerSlug: "xcel-energy" }
] as const;
