import type { CompanyProfile } from "@/lib/companies/types";

const PILOT_COMPANIES = [
  {
    slug: "investor",
    name: "Investor",
    displayName: "Investor B",
    ticker: "INVE B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Finans",
    founded: "1916",
    headquarters: "Stockholm",
    shortDescription:
      "Investmentbolag med långsiktiga ägarintressen i ledande nordiska och internationella bolag.",
    description:
      "Investor är ett svenskt investmentbolag med fokus på aktivt och långsiktigt ägande i noterade bolag och helägda verksamheter.",
    websiteLabel: "investorab.com",
    websiteUrl: "https://www.investorab.com/",
    pressReleasesUrl:
      "https://www.investorab.com/investors-media/press-releases",
    reportsUrl:
      "https://www.investorab.com/investors-media/reports-presentations/",
    calendarUrl:
      "https://www.investorab.com/investors-media/events-calendar",
    ownershipUrl:
      "https://www.investorab.com/investors-media/the-investor-share/ownership-structure",
    governanceUrl:
      "https://www.investorab.com/about-investor/board-management/executive-leadership-team",
    linkedinUrl: "https://www.linkedin.com/company/investor-ab",
    relatedSlugs: ["atlas-copco", "ericsson", "volvo"],
    tradingViewSymbol: "OMXSTO:INVE_B",
    marketDataSymbol: "INVE-B.ST",
    logoPath: "/company-logos/investor.svg",
    aliases: ["Investor", "Investor AB"],
    tickerAliases: ["INVE B", "INVE-B", "INVE_B"],
  },
  {
    slug: "volvo",
    name: "Volvo",
    displayName: "Volvo B",
    ticker: "VOLV B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Industri",
    founded: "1927",
    headquarters: "Göteborg",
    shortDescription:
      "Global tillverkare av lastbilar, bussar, anläggningsmaskiner samt marina och industriella drivsystem.",
    description:
      "Volvo Group är en global industrikoncern som utvecklar transportlösningar och infrastruktursystem för professionella kunder.",
    websiteLabel: "volvogroup.com",
    websiteUrl: "https://www.volvogroup.com/",
    pressReleasesUrl: "https://www.volvogroup.com/en/news-and-media.html",
    reportsUrl:
      "https://www.volvogroup.com/en/investors/reports-and-presentations.html",
    calendarUrl:
      "https://www.volvogroup.com/en/investors/financial-calendar.html",
    relatedSlugs: ["atlas-copco", "ericsson", "investor"],
    tradingViewSymbol: "OMXSTO:VOLV_B",
    marketDataSymbol: "VOLV-B.ST",
    logoPath: "/company-logos/volvo.svg",
    aliases: ["Volvo", "AB Volvo", "Volvo Group"],
    tickerAliases: ["VOLV B", "VOLV-B", "VOLV_B"],
  },
  {
    slug: "ericsson",
    name: "Ericsson",
    displayName: "Ericsson B",
    ticker: "ERIC B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Teknik",
    founded: "1876",
    headquarters: "Stockholm",
    shortDescription:
      "Global leverantör av kommunikationsteknik, nätverksutrustning och digital infrastruktur.",
    description:
      "Ericsson utvecklar nätverk, mjukvara och tjänster för telekomoperatörer och andra aktörer inom digital infrastruktur.",
    websiteLabel: "ericsson.com",
    websiteUrl: "https://www.ericsson.com/",
    pressReleasesUrl:
      "https://www.ericsson.com/en/newsroom/latest-news?locs=68304&typeFilters=3",
    reportsUrl:
      "https://www.ericsson.com/en/investors/financial-reports-and-presentations",
    calendarUrl: "https://www.ericsson.com/en/investors/financial-calendar",
    relatedSlugs: ["investor", "volvo", "atlas-copco"],
    tradingViewSymbol: "OMXSTO:ERIC_B",
    marketDataSymbol: "ERIC-B.ST",
    logoPath: "/company-logos/ericsson.svg",
    aliases: ["Ericsson", "Telefonaktiebolaget LM Ericsson"],
    tickerAliases: ["ERIC B", "ERIC-B", "ERIC_B"],
  },
  {
    slug: "atlas-copco",
    name: "Atlas Copco",
    displayName: "Atlas Copco A",
    ticker: "ATCO A",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Industri",
    founded: "1873",
    headquarters: "Nacka",
    shortDescription:
      "Global industrikoncern inom kompressorer, vakuumteknik, energilösningar och industriteknik.",
    description:
      "Atlas Copco utvecklar produkter, tjänster och system som höjer produktivitet, energieffektivitet och säkerhet i industriella verksamheter.",
    websiteLabel: "atlascopcogroup.com",
    websiteUrl: "https://www.atlascopcogroup.com/",
    pressReleasesUrl:
      "https://www.atlascopcogroup.com/en/media/press-releases",
    reportsUrl:
      "https://www.atlascopcogroup.com/en/investors/reports-and-presentations",
    calendarUrl:
      "https://www.atlascopcogroup.com/en/investors/calendar-and-events",
    relatedSlugs: ["volvo", "investor", "ericsson"],
    tradingViewSymbol: "OMXSTO:ATCO_A",
    marketDataSymbol: "ATCO-A.ST",
    logoPath: null,
    aliases: ["Atlas Copco", "Atlas Copco AB"],
    tickerAliases: ["ATCO A", "ATCO-A", "ATCO_A"],
  },
  {
    slug: "astrazeneca",
    name: "AstraZeneca",
    displayName: "AstraZeneca",
    ticker: "AZN",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Hälsovård",
    founded: "1999",
    headquarters: "Cambridge, Storbritannien",
    shortDescription:
      "Globalt forskningsdrivet läkemedelsbolag med fokus på bland annat onkologi och sällsynta sjukdomar.",
    description:
      "AstraZeneca forskar, utvecklar och kommersialiserar receptbelagda läkemedel med global verksamhet och notering i Stockholm.",
    websiteLabel: "astrazeneca.com",
    websiteUrl: "https://www.astrazeneca.com/",
    pressReleasesUrl:
      "https://www.astrazeneca.com/media-centre/press-releases.html",
    reportsUrl:
      "https://www.astrazeneca.com/investor-relations/results-and-presentations.html",
    calendarUrl:
      "https://www.astrazeneca.com/investor-relations/events.html",
    relatedSlugs: ["investor", "ericsson", "atlas-copco"],
    tradingViewSymbol: "OMXSTO:AZN",
    marketDataSymbol: "AZN.ST",
    logoPath: null,
    aliases: ["AstraZeneca", "AstraZeneca PLC"],
    tickerAliases: ["AZN"],
  },
  {
    slug: "abb",
    name: "ABB",
    displayName: "ABB",
    ticker: "ABB",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Industri",
    founded: "1988",
    headquarters: "Zürich",
    shortDescription:
      "Global teknikkoncern inom elektrifiering, automation, robotik och drivsystem.",
    description:
      "ABB utvecklar elektrifiering, processautomation, rörelse och robotik för industri- och infrastrukturkunder, med notering på Nasdaq Stockholm.",
    websiteLabel: "global.abb",
    websiteUrl: "https://global.abb/group/en",
    pressReleasesUrl: "https://global.abb/group/en",
    reportsUrl: "https://global.abb/group/en",
    calendarUrl: "https://global.abb/group/en",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:ABB",
    marketDataSymbol: "ABB.ST",
    logoPath: null,
    aliases: ["ABB", "ABB Ltd"],
    tickerAliases: ["ABB"],
  },
  {
    slug: "addtech",
    name: "Addtech",
    displayName: "Addtech B",
    ticker: "ADDT B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Industri",
    founded: "2001",
    headquarters: "Stockholm",
    shortDescription:
      "Teknikhandelskoncern som utvecklar och säljer högteknologiska produkter och lösningar.",
    description:
      "Addtech är en svensk teknikhandelskoncern med nischade bolag inom industriella komponenter, system och lösningar.",
    websiteLabel: "addtech.com",
    websiteUrl: "https://www.addtech.com/investors",
    pressReleasesUrl: "https://www.addtech.com/investors",
    reportsUrl: "https://www.addtech.com/investors",
    calendarUrl: "https://www.addtech.com/investors",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:ADDT_B",
    marketDataSymbol: "ADDT-B.ST",
    logoPath: null,
    aliases: ["Addtech", "Addtech AB"],
    tickerAliases: ["ADDT B", "ADDT-B", "ADDT_B"],
  },
  {
    slug: "alfa-laval",
    name: "Alfa Laval",
    displayName: "Alfa Laval",
    ticker: "ALFA",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Industri",
    founded: "1883",
    headquarters: "Lund",
    shortDescription:
      "Global leverantör av värmeöverföring, separering och flödeshantering.",
    description:
      "Alfa Laval utvecklar produkter och lösningar för värmeöverföring, separering och flödeshantering inom industri, energi och livsmedel.",
    websiteLabel: "alfalaval.com",
    websiteUrl: "https://www.alfalaval.com/investors/",
    pressReleasesUrl: "https://www.alfalaval.com/investors/",
    reportsUrl: "https://www.alfalaval.com/investors/",
    calendarUrl: "https://www.alfalaval.com/investors/",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:ALFA",
    marketDataSymbol: "ALFA.ST",
    logoPath: null,
    aliases: ["Alfa Laval", "Alfa Laval AB"],
    tickerAliases: ["ALFA"],
  },
  {
    slug: "assa-abloy",
    name: "ASSA ABLOY",
    displayName: "ASSA ABLOY B",
    ticker: "ASSA B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Industri",
    founded: "1994",
    headquarters: "Stockholm",
    shortDescription:
      "Global koncern inom lås, dörrar och tillträdeslösningar.",
    description:
      "ASSA ABLOY utvecklar lås, dörrlösningar och tillträdeskontroll för hem, företag och institutioner.",
    websiteLabel: "assaabloy.com",
    websiteUrl: "https://www.assaabloy.com/group/en/investors",
    pressReleasesUrl: "https://www.assaabloy.com/group/en/investors",
    reportsUrl: "https://www.assaabloy.com/group/en/investors",
    calendarUrl: "https://www.assaabloy.com/group/en/investors",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:ASSA_B",
    marketDataSymbol: "ASSA-B.ST",
    logoPath: null,
    aliases: ["ASSA ABLOY", "Assa Abloy"],
    tickerAliases: ["ASSA B", "ASSA-B", "ASSA_B"],
  },
  {
    slug: "boliden",
    name: "Boliden",
    displayName: "Boliden",
    ticker: "BOL",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Material",
    founded: "1924",
    headquarters: "Stockholm",
    shortDescription:
      "Metallbolag med gruvor och smältverk för basmetaller och ädelmetaller.",
    description:
      "Boliden utvinner och förädlar basmetaller och ädelmetaller genom gruvor och smältverk i Norden och Europa.",
    websiteLabel: "boliden.com",
    websiteUrl: "https://www.boliden.com/investor-relations/",
    pressReleasesUrl: "https://www.boliden.com/investor-relations/",
    reportsUrl: "https://www.boliden.com/investor-relations/",
    calendarUrl: "https://www.boliden.com/investor-relations/",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:BOL",
    marketDataSymbol: "BOL.ST",
    logoPath: null,
    aliases: ["Boliden", "Boliden AB"],
    tickerAliases: ["BOL"],
  },
  {
    slug: "epiroc",
    name: "Epiroc",
    displayName: "Epiroc A",
    ticker: "EPI A",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Industri",
    founded: "2018",
    headquarters: "Stockholm",
    shortDescription:
      "Leverantör av utrustning och service för gruv- och infrastrukturindustrin.",
    description:
      "Epiroc utvecklar borriggar, bergbrytningsutrustning, verktyg och service för gruvor och anläggningsprojekt.",
    websiteLabel: "epirocgroup.com",
    websiteUrl: "https://www.epirocgroup.com/en/investors",
    pressReleasesUrl: "https://www.epirocgroup.com/en/media/corporate-press-releases",
    reportsUrl: "https://www.epirocgroup.com/en/investors",
    calendarUrl: "https://www.epirocgroup.com/en/investors/financial-calendar1",
    relatedSlugs: ["investor", "volvo", "atlas-copco"],
    tradingViewSymbol: "OMXSTO:EPI_A",
    marketDataSymbol: "EPI-A.ST",
    logoPath: null,
    aliases: ["Epiroc", "Epiroc AB"],
    tickerAliases: ["EPI A", "EPI-A", "EPI_A"],
  },
  {
    slug: "eqt",
    name: "EQT",
    displayName: "EQT",
    ticker: "EQT",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Finans",
    founded: "1994",
    headquarters: "Stockholm",
    shortDescription:
      "Global investeringsorganisation med fonder inom private equity och infrastruktur.",
    description:
      "EQT är en global investeringsorganisation som förvaltar fonder och investerar i bolag och tillgångar tillsammans med sina investerare.",
    websiteLabel: "eqtgroup.com",
    websiteUrl: "https://eqtgroup.com/",
    pressReleasesUrl: "https://eqtgroup.com/shareholders",
    reportsUrl: "https://eqtgroup.com/shareholders",
    calendarUrl: "https://eqtgroup.com/shareholders/financial-calendar",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:EQT",
    marketDataSymbol: "EQT.ST",
    logoPath: null,
    aliases: ["EQT", "EQT AB"],
    tickerAliases: ["EQT"],
  },
  {
    slug: "essity",
    name: "Essity",
    displayName: "Essity B",
    ticker: "ESSITY B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Konsument",
    founded: "2017",
    headquarters: "Stockholm",
    shortDescription:
      "Hygien- och hälsobolag med produkter inom mjukpapper, inkontinens och sårvård.",
    description:
      "Essity utvecklar och säljer hygien- och hälsoprodukter för konsumenter, företag och vårdverksamheter.",
    websiteLabel: "essity.com",
    websiteUrl: "https://www.essity.com/investors/",
    pressReleasesUrl: "https://www.essity.com/investors/",
    reportsUrl: "https://www.essity.com/investors/",
    calendarUrl: "https://www.essity.com/investors/",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:ESSITY_B",
    marketDataSymbol: "ESSITY-B.ST",
    logoPath: null,
    aliases: ["Essity", "Essity AB"],
    tickerAliases: ["ESSITY B", "ESSITY-B", "ESSITY_B"],
  },
  {
    slug: "evolution",
    name: "Evolution",
    displayName: "Evolution",
    ticker: "EVO",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Konsument",
    founded: "2006",
    headquarters: "Stockholm",
    shortDescription:
      "Leverantör av livekasino och andra spelprodukter till operatörer.",
    description:
      "Evolution utvecklar och driver livekasino och andra B2B-spelprodukter för speloperatörer.",
    websiteLabel: "evolution.com",
    websiteUrl: "https://www.evolution.com/investors/",
    pressReleasesUrl: "https://www.evolution.com/investors/",
    reportsUrl: "https://www.evolution.com/investors/",
    calendarUrl: "https://www.evolution.com/investors/",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:EVO",
    marketDataSymbol: "EVO.ST",
    logoPath: null,
    aliases: ["Evolution", "Evolution AB"],
    tickerAliases: ["EVO"],
  },
  {
    slug: "handelsbanken",
    name: "Handelsbanken",
    displayName: "Handelsbanken A",
    ticker: "SHB A",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Finans",
    founded: "1871",
    headquarters: "Stockholm",
    shortDescription:
      "Svensk bank med kontorsrörelse och tjänster för privat- och företagskunder.",
    description:
      "Handelsbanken är en svensk bank som erbjuder tjänster för privatkunder, företag och institutioner.",
    websiteLabel: "handelsbanken.com",
    websiteUrl: "https://www.handelsbanken.com/en/investor-relations",
    pressReleasesUrl: "https://www.handelsbanken.com/en/investor-relations",
    reportsUrl: "https://www.handelsbanken.com/en/investor-relations",
    calendarUrl: "https://www.handelsbanken.com/en/investor-relations",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:SHB_A",
    marketDataSymbol: "SHB-A.ST",
    logoPath: null,
    aliases: ["Handelsbanken", "Svenska Handelsbanken"],
    tickerAliases: ["SHB A", "SHB-A", "SHB_A"],
  },
  {
    slug: "hm",
    name: "H&M",
    displayName: "H&M B",
    ticker: "HM B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Konsument",
    founded: "1947",
    headquarters: "Stockholm",
    shortDescription:
      "Globalt modebolag med butiker och e-handel under flera varumärken.",
    description:
      "H&M-gruppen designar och säljer kläder, accessoarer och hemtextil genom egna butiker och digitala kanaler.",
    websiteLabel: "hmgroup.com",
    websiteUrl: "https://hmgroup.com/investors/",
    pressReleasesUrl: "https://hmgroup.com/investors/",
    reportsUrl: "https://hmgroup.com/investors/",
    calendarUrl: "https://hmgroup.com/investors/",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:HM_B",
    marketDataSymbol: "HM-B.ST",
    logoPath: "/company-logos/hm.svg",
    aliases: ["H&M", "Hennes & Mauritz", "H & M"],
    tickerAliases: ["HM B", "HM-B", "HM_B"],
  },
  {
    slug: "hexagon",
    name: "Hexagon",
    displayName: "Hexagon B",
    ticker: "HEXA B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Teknik",
    founded: "1992",
    headquarters: "Stockholm",
    shortDescription:
      "Teknikbolag inom mätteknik, sensorer och digitala verklighetslösningar.",
    description:
      "Hexagon utvecklar sensorer, mjukvara och autonoma lösningar som används för att mäta och visualisera den fysiska världen.",
    websiteLabel: "hexagon.com",
    websiteUrl: "https://hexagon.com/investors",
    pressReleasesUrl: "https://hexagon.com/company/newsroom/press-releases",
    reportsUrl: "https://hexagon.com/investors",
    calendarUrl: "https://hexagon.com/investors",
    relatedSlugs: ["investor", "ericsson", "atlas-copco"],
    tradingViewSymbol: "OMXSTO:HEXA_B",
    marketDataSymbol: "HEXA-B.ST",
    logoPath: null,
    aliases: ["Hexagon", "Hexagon AB"],
    tickerAliases: ["HEXA B", "HEXA-B", "HEXA_B"],
  },
  {
    slug: "industrivarden",
    name: "Industrivärden",
    displayName: "Industrivärden C",
    ticker: "INDU C",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Finans",
    founded: "1944",
    headquarters: "Stockholm",
    shortDescription:
      "Investmentbolag med långsiktigt ägande i nordiska börsbolag.",
    description:
      "Industrivärden är ett svenskt investmentbolag som utövar långsiktigt aktivt ägande i en koncentrerad portfölj av börsnoterade bolag.",
    websiteLabel: "industrivarden.se",
    websiteUrl: "https://www.industrivarden.se/",
    pressReleasesUrl: "https://www.industrivarden.se/media/Pressmeddelanden/",
    reportsUrl: "https://www.industrivarden.se/",
    calendarUrl: "https://www.industrivarden.se/investerare/Kalender/",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:INDU_C",
    marketDataSymbol: "INDU-C.ST",
    logoPath: null,
    aliases: ["Industrivärden", "AB Industrivärden"],
    tickerAliases: ["INDU C", "INDU-C", "INDU_C"],
  },
  {
    slug: "lifco",
    name: "Lifco",
    displayName: "Lifco B",
    ticker: "LIFCO B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Industri",
    founded: "1946",
    headquarters: "Enköping",
    shortDescription:
      "Industrikoncern med nischade bolag inom dental, system och demontering.",
    description:
      "Lifco äger och utvecklar nischade bolag inom dental, demoleringsverktyg och andra industriella systemlösningar.",
    websiteLabel: "lifco.se",
    websiteUrl: "https://www.lifco.se/",
    pressReleasesUrl: "https://www.lifco.se/investors/",
    reportsUrl: "https://www.lifco.se/investors/",
    calendarUrl: "https://www.lifco.se/investors/",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:LIFCO_B",
    marketDataSymbol: "LIFCO-B.ST",
    logoPath: null,
    aliases: ["Lifco", "Lifco AB"],
    tickerAliases: ["LIFCO B", "LIFCO-B", "LIFCO_B"],
  },
  {
    slug: "nibe",
    name: "NIBE",
    displayName: "NIBE B",
    ticker: "NIBE B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Industri",
    founded: "1952",
    headquarters: "Markaryd",
    shortDescription:
      "Tillverkare av värmepumpar, kaminer och industriella värmelösningar.",
    description:
      "NIBE Industrier utvecklar och tillverkar värmepumpar, brasvärme och industriella värmesystem.",
    websiteLabel: "nibe.com",
    websiteUrl: "https://www.nibe.com/investors",
    pressReleasesUrl: "https://www.nibe.com/investors",
    reportsUrl: "https://www.nibe.com/investors",
    calendarUrl: "https://www.nibe.com/investors",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:NIBE_B",
    marketDataSymbol: "NIBE-B.ST",
    logoPath: null,
    aliases: ["NIBE", "NIBE Industrier"],
    tickerAliases: ["NIBE B", "NIBE-B", "NIBE_B"],
  },
  {
    slug: "nordea",
    name: "Nordea",
    displayName: "Nordea",
    ticker: "NDA SE",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Finans",
    founded: "2000",
    headquarters: "Helsingfors",
    shortDescription:
      "Nordisk bank med tjänster för privatpersoner, företag och institutioner.",
    description:
      "Nordea är en nordisk bank med notering i Stockholm. Banken erbjuder tjänster för privatpersoner, företag och institutionella kunder.",
    websiteLabel: "nordea.com",
    websiteUrl: "https://www.nordea.com/en/investors",
    pressReleasesUrl: "https://www.nordea.com/en/investors",
    reportsUrl: "https://www.nordea.com/en/investors",
    calendarUrl: "https://www.nordea.com/en/investors",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:NDA_SE",
    marketDataSymbol: "NDA-SE.ST",
    logoPath: null,
    aliases: ["Nordea", "Nordea Bank"],
    tickerAliases: ["NDA SE", "NDA-SE", "NDA_SE"],
  },
  {
    slug: "saab",
    name: "Saab",
    displayName: "Saab B",
    ticker: "SAAB B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Industri",
    founded: "1937",
    headquarters: "Stockholm",
    shortDescription:
      "Försvars- och säkerhetsbolag inom flyg, sensorer och ledningssystem.",
    description:
      "Saab utvecklar produkter och system för försvar och säkerhet, bland annat flyg, sensorer och ledningssystem.",
    websiteLabel: "saab.com",
    websiteUrl: "https://www.saab.com/investors",
    pressReleasesUrl: "https://www.saab.com/investors",
    reportsUrl: "https://www.saab.com/investors",
    calendarUrl: "https://www.saab.com/investors",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:SAAB_B",
    marketDataSymbol: "SAAB-B.ST",
    logoPath: null,
    aliases: ["Saab", "Saab AB"],
    tickerAliases: ["SAAB B", "SAAB-B", "SAAB_B"],
  },
  {
    slug: "sandvik",
    name: "Sandvik",
    displayName: "Sandvik",
    ticker: "SAND",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Industri",
    founded: "1862",
    headquarters: "Stockholm",
    shortDescription:
      "Industrikoncern inom gruvutrustning, bergbearbetning och tillverkning.",
    description:
      "Sandvik utvecklar utrustning, verktyg och tjänster för gruvindustri och tillverkande industri.",
    websiteLabel: "home.sandvik",
    websiteUrl: "https://www.home.sandvik/en/investors/",
    pressReleasesUrl: "https://www.home.sandvik/en/investors/",
    reportsUrl: "https://www.home.sandvik/en/investors/",
    calendarUrl: "https://www.home.sandvik/en/investors/",
    relatedSlugs: ["investor", "volvo", "atlas-copco"],
    tradingViewSymbol: "OMXSTO:SAND",
    marketDataSymbol: "SAND.ST",
    logoPath: null,
    aliases: ["Sandvik", "Sandvik AB"],
    tickerAliases: ["SAND"],
  },
  {
    slug: "sca",
    name: "SCA",
    displayName: "SCA B",
    ticker: "SCA B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Material",
    founded: "1929",
    headquarters: "Sundsvall",
    shortDescription:
      "Skogsbolag med skog, trä, massa och förnybar energi.",
    description:
      "SCA äger skog och tillverkar träprodukter, massa och förpackningsmaterial samt producerar förnybar energi.",
    websiteLabel: "sca.com",
    websiteUrl: "https://www.sca.com/en/investors/",
    pressReleasesUrl: "https://www.sca.com/en/investors/",
    reportsUrl: "https://www.sca.com/en/investors/",
    calendarUrl: "https://www.sca.com/en/investors/",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:SCA_B",
    marketDataSymbol: "SCA-B.ST",
    logoPath: null,
    aliases: ["SCA", "Svenska Cellulosa Aktiebolaget"],
    tickerAliases: ["SCA B", "SCA-B", "SCA_B"],
  },
  {
    slug: "seb",
    name: "SEB",
    displayName: "SEB A",
    ticker: "SEB A",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Finans",
    founded: "1856",
    headquarters: "Stockholm",
    shortDescription:
      "Nordisk bank för företag, institutioner och privatkunder.",
    description:
      "SEB är en nordisk bank som erbjuder finansiella tjänster till företag, institutioner och privatkunder.",
    websiteLabel: "sebgroup.com",
    websiteUrl: "https://sebgroup.com/investor-relations",
    pressReleasesUrl: "https://sebgroup.com/investor-relations",
    reportsUrl: "https://sebgroup.com/investor-relations",
    calendarUrl: "https://sebgroup.com/investor-relations",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:SEB_A",
    marketDataSymbol: "SEB-A.ST",
    logoPath: null,
    aliases: ["SEB", "Skandinaviska Enskilda Banken"],
    tickerAliases: ["SEB A", "SEB-A", "SEB_A"],
  },
  {
    slug: "skanska",
    name: "Skanska",
    displayName: "Skanska B",
    ticker: "SKA B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Industri",
    founded: "1887",
    headquarters: "Stockholm",
    shortDescription:
      "Bygg- och projektutvecklingsbolag med verksamhet i Norden, Europa och USA.",
    description:
      "Skanska bedriver byggverksamhet och projektutveckling av kommersiella fastigheter, bostäder och infrastruktur.",
    websiteLabel: "skanska.com",
    websiteUrl: "https://www.skanska.com/investors/",
    pressReleasesUrl: "https://www.skanska.com/investors/",
    reportsUrl: "https://www.skanska.com/investors/",
    calendarUrl: "https://www.skanska.com/investors/",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:SKA_B",
    marketDataSymbol: "SKA-B.ST",
    logoPath: null,
    aliases: ["Skanska", "Skanska AB"],
    tickerAliases: ["SKA B", "SKA-B", "SKA_B"],
  },
  {
    slug: "skf",
    name: "SKF",
    displayName: "SKF B",
    ticker: "SKF B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Industri",
    founded: "1907",
    headquarters: "Göteborg",
    shortDescription:
      "Tillverkare av lager, tätningar och smörjsystem för roterande utrustning.",
    description:
      "SKF utvecklar lager, tätningar, smörjsystem och tjänster som används i roterande maskiner.",
    websiteLabel: "skf.com",
    websiteUrl: "https://www.skf.com/group/investors",
    pressReleasesUrl: "https://www.skf.com/group/investors",
    reportsUrl: "https://www.skf.com/group/investors",
    calendarUrl: "https://www.skf.com/group/investors",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:SKF_B",
    marketDataSymbol: "SKF-B.ST",
    logoPath: null,
    aliases: ["SKF", "AB SKF"],
    tickerAliases: ["SKF B", "SKF-B", "SKF_B"],
  },
  {
    slug: "swedbank",
    name: "Swedbank",
    displayName: "Swedbank A",
    ticker: "SWED A",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Finans",
    founded: "1820",
    headquarters: "Stockholm",
    shortDescription:
      "Svensk bank med stark ställning bland privat- och företagskunder i Norden och Baltikum.",
    description:
      "Swedbank erbjuder banktjänster för privatpersoner, företag och den offentliga sektorn, med huvudmarknader i Sverige och Baltikum.",
    websiteLabel: "swedbank.com",
    websiteUrl: "https://www.swedbank.com/investor-relations.html",
    pressReleasesUrl: "https://www.swedbank.com/investor-relations.html",
    reportsUrl: "https://www.swedbank.com/investor-relations.html",
    calendarUrl: "https://www.swedbank.com/investor-relations.html",
    relatedSlugs: ["investor", "volvo", "ericsson"],
    tradingViewSymbol: "OMXSTO:SWED_A",
    marketDataSymbol: "SWED-A.ST",
    logoPath: null,
    aliases: ["Swedbank", "Swedbank AB"],
    tickerAliases: ["SWED A", "SWED-A", "SWED_A"],
  },
  {
    slug: "tele2",
    name: "Tele2",
    displayName: "Tele2 B",
    ticker: "TEL2 B",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Telekom",
    founded: "1993",
    headquarters: "Stockholm",
    shortDescription:
      "Telekomoperatör med mobil-, bredbands- och företagstjänster.",
    description:
      "Tele2 tillhandahåller mobiltelefoni, bredband och andra anslutningstjänster för privat- och företagskunder.",
    websiteLabel: "tele2.com",
    websiteUrl: "https://www.tele2.com/investors",
    pressReleasesUrl: "https://www.tele2.com/investors",
    reportsUrl: "https://www.tele2.com/investors",
    calendarUrl: "https://www.tele2.com/investors",
    relatedSlugs: ["investor", "ericsson", "astrazeneca"],
    tradingViewSymbol: "OMXSTO:TEL2_B",
    marketDataSymbol: "TEL2-B.ST",
    logoPath: null,
    aliases: ["Tele2", "Tele2 AB"],
    tickerAliases: ["TEL2 B", "TEL2-B", "TEL2_B"],
  },
  {
    slug: "telia",
    name: "Telia",
    displayName: "Telia",
    ticker: "TELIA",
    exchange: "Nasdaq Stockholm",
    countryCode: "SE",
    countryName: "Sverige",
    segment: "Large Cap",
    sector: "Telekom",
    founded: "1853",
    headquarters: "Stockholm",
    shortDescription:
      "Telekomkoncern med nät, telefoni och digitala tjänster i Norden och Baltikum.",
    description:
      "Telia Company driver telekomnät och erbjuder telefoni, bredband och digitala tjänster i Norden och Baltikum.",
    websiteLabel: "teliacompany.com",
    websiteUrl: "https://www.teliacompany.com/en/investors",
    pressReleasesUrl: "https://www.teliacompany.com/en/investors",
    reportsUrl: "https://www.teliacompany.com/en/investors",
    calendarUrl: "https://www.teliacompany.com/en/investors",
    relatedSlugs: ["investor", "ericsson", "astrazeneca"],
    tradingViewSymbol: "OMXSTO:TELIA",
    marketDataSymbol: "TELIA.ST",
    logoPath: null,
    aliases: ["Telia", "Telia Company"],
    tickerAliases: ["TELIA"],
  },
] as const satisfies readonly CompanyProfile[];

export function getPilotCompanies(): readonly CompanyProfile[] {
  return PILOT_COMPANIES;
}

export function getCompanyProfile(slug: string): CompanyProfile | null {
  return PILOT_COMPANIES.find((company) => company.slug === slug) ?? null;
}

export function getRelatedCompanies(
  company: CompanyProfile,
): readonly CompanyProfile[] {
  const relatedSlugs = new Set(company.relatedSlugs);

  return PILOT_COMPANIES.filter((candidate) => relatedSlugs.has(candidate.slug));
}
