import type { NavigationItem } from "@/types/navigation";

export const appNavigation: NavigationItem[] = [
  { label: "Start", href: "/dashboard", icon: "dashboard" },
  {
    label: "Frihetsmaskinen",
    href: "/frihetsmaskinen",
    icon: "goals",
    visibility: "mobile-only",
  },
  { label: "Portfölj", href: "/portfolio", icon: "portfolio" },
  { label: "Dividend Brain", href: "/brain", icon: "brain" },
  { label: "Bevakningslista", href: "/watchlist", icon: "watchlist" },
  { label: "Börsnyheter", href: "/news", icon: "news" },
  { label: "Forum", href: "/forum", icon: "forum" },
  { label: "Meddelanden", href: "/messages", icon: "messages" },
  { label: "Utbildning", href: "/learning", icon: "learning" },
  { label: "Mål", href: "/goals", icon: "goals" },
  { label: "Kalender", href: "/calendar", icon: "calendar" },
  { label: "Konto", href: "/account", icon: "account" },
  { label: "Inställningar", href: "/settings", icon: "settings" },
];

export const pageTitles: Record<string, string> = {
  "/account": "Investeraridentitet",
  "/account/edit": "Redigera profil",
  "/brain": "Dividend Brain",
  "/calendar": "Kalender",
  "/dashboard": "Start",
  "/frihetsmaskinen": "Frihetsmaskinen",
  "/forum": "Forum",
  "/forum/senaste": "Senaste",
  "/forum/populart": "Populärt",
  "/forum/kategorier": "Kategorier",
  "/forum/bolag": "Bolag",
  "/forum/regler": "Forumregler",
  "/goals": "Mål",
  "/learning": "Utbildning",
  "/messages": "Meddelanden",
  "/messages/new": "Nytt meddelande",
  "/news": "Börsnyheter",
  "/portfolio": "Portfölj",
  "/settings": "Inställningar",
  "/watchlist": "Bevakningslista",
  "/profile": "Profil",
  "/dashboard/account": "Investeraridentitet",
  "/dashboard/brain": "Dividend Brain",
  "/dashboard/forum": "Forum",
  "/dashboard/goals": "Mål",
  "/dashboard/learning": "Utbildning",
  "/dashboard/portfolio": "Portfölj",
  "/dashboard/settings": "Inställningar",
  "/dashboard/watchlist": "Bevakningslista",
};
