import { VECKAN_SOM_GATT_29_AUGUSTI_2026_ARTICLE } from "@/data/news-articles/veckan-som-gatt-29-augusti-2026";
import { BORSSVERIGE_28_AUGUSTI_2026_ARTICLE } from "@/data/news-articles/borssverige-28-augusti-2026";
import { NORDEN_I_CENTRUM_28_AUGUSTI_2026_ARTICLE } from "@/data/news-articles/norden-i-centrum-28-augusti-2026";
import { BORSSVERIGE_27_AUGUSTI_2026_ARTICLE } from "@/data/news-articles/borssverige-27-augusti-2026";
import { USA_BORSEN_NVIDIA_NASDAQ_AI_RALLY_27_AUGUSTI_2026_ARTICLE } from "@/data/news-articles/usa-borsen-nvidia-nasdaq-ai-rally-27-augusti-2026";
import { DEMO_NEWS_ARTICLES } from "@/data/news-demo";
import { applyNewsSearchSeo } from "@/lib/seo/editorial-content";
import type { NewsArticle } from "@/types/news";

/**
 * Historical editor uploads used autogenerated filenames. The physical assets
 * have been renamed to readable filenames, while article source files remain
 * stable. Resolve legacy paths here so published articles keep working without
 * duplicating or retaining opaque files in /public/news-demo.
 *
 * The canonical DivLab logo reference is intentionally NOT aliased:
 * /news-demo/file_000000009cf48246883ae568fc196154.png
 */
const NEWS_IMAGE_ASSET_ALIASES: Readonly<Record<string, string>> = {
  "/news-demo/file_00000000e9608211b716d4b8480d634b.png":
    "/news-demo/ai-handeln-wall-street-nvidia-2026-08-24.png",
  "/news-demo/file_00000000c794820a8db16763aebb3bf0.png":
    "/news-demo/borssverige-2026-08-24.png",
  "/news-demo/file_000000002988820aa371cdcc766f52e4.png":
    "/news-demo/norden-i-centrum-2026-08-24.png",
  "/news-demo/file_0000000029108246b664b7b3ad7dee25.png":
    "/news-demo/borsveckan-nvidia-jackson-hole-2026-08-24.png",
  "/news-demo/file_00000000fcdc82439565f9cc07641119.png":
    "/news-demo/teknisk-analys-evolution-2026-08-23.png",
  "/news-demo/Skärmbild 2026-08-23 214755.png":
    "/news-demo/evolution-teknisk-analys-diagram-2026-08-23.png",
  "/news-demo/file_000000002e8881f4906751457a95758c.png":
    "/news-demo/veckan-som-gatt-2026-08-21.png",
  "/news-demo/file_00000000dee08246a2e591a5e6777caa.png":
    "/news-demo/borssverige-2026-08-21.png",
  "/news-demo/file_000000008c7c820a8107e635bab3f1c1.png":
    "/news-demo/norden-i-centrum-2026-08-21.png",
  "/news-demo/file_000000009ea081f48c7e6ea2a35c5003.png":
    "/news-demo/hufvudstaden-fastigheter-2026-08-20.png",
  "/news-demo/file_00000000d8f8820aa8af012c4f0489c4.png":
    "/news-demo/borssverige-lunch-2026-08-20.png",
  "/news-demo/file_00000000cbc0820a883f995380e36b4e.png":
    "/news-demo/borssverige-holmen-riksbanken-2026-08-20.png",
  "/news-demo/file_000000008bfc81f4996035ae844945f2.png":
    "/news-demo/norden-i-centrum-2026-08-20.png",
  "/news-demo/file_00000000ccf8820aab0faf9406788a9f.png":
    "/news-demo/ai-frossa-wall-street-chipjattar-2026-08-19.png",
  "/news-demo/file_00000000d078820a93662e7928a9d5cf.png":
    "/news-demo/borssverige-lunch-2026-08-19.png",
  "/news-demo/file_0000000023fc8246bf8e4c00765736b3.png":
    "/news-demo/latour-q2-2026-08-19.png",
  "/news-demo/file_0000000013e481f49e37dbf50e4ef5b8.png":
    "/news-demo/borssverige-2026-08-19.png",
  "/news-demo/file_00000000e114820ab7fe53313df8d3ee.png":
    "/news-demo/techfrossa-wall-street-nvidia-2026-08-18.png",
  "/news-demo/file_000000004b1081f4bc3de58d4eeb387b.png":
    "/news-demo/hemnet-jp-morgan-2026-08-18.png",
  "/news-demo/file_00000000bdfc81f496784f507593fadb.png":
    "/news-demo/bahnhof-q2-2026-08-18.png",
  "/news-demo/file_0000000035a4820a9bdf5f37dbbf7bb9.png":
    "/news-demo/norden-i-centrum-2026-08-18.png",
  "/news-demo/ChatGPT Image 16 aug. 2026 22_25_40.png":
    "/news-demo/borsveckan-vecka-33-34-2026.png",
  "/news-demo/file_00000000b8a082119997b753d8eeff30.png":
    "/news-demo/reddit-sp500-2026-08-14.png",
  "/news-demo/file_00000000a0f48246ac69ef1f82c8430f.png":
    "/news-demo/borssverige-2026-08-14.png",
  "/news-demo/file_00000000948c8243afd5896acc7c8754.png":
    "/news-demo/norden-i-centrum-2026-08-14.png",
  "/news-demo/file_0000000082488211b2dbe615932a6b79.png":
    "/news-demo/borssverige-lunch-2026-08-13.png",
  "/news-demo/file_00000000b36881f489650afecf2504af.png":
    "/news-demo/evolution-budpliktsbud-2026-08-13.png",
  "/news-demo/file_000000000cd481f490eaf05c20ba7c0c.png":
    "/news-demo/wall-street-rekord-inflation-tech-2026-08-13.png",
};

function resolveNewsImagePath(path: string): string {
  return NEWS_IMAGE_ASSET_ALIASES[path] ?? path;
}

function resolveOptionalNewsImagePath(
  path: string | null | undefined,
): string | null | undefined {
  return path ? resolveNewsImagePath(path) : path;
}

function resolveNewsArticleImages(article: NewsArticle): NewsArticle {
  return {
    ...article,
    imageUrl: resolveOptionalNewsImagePath(article.imageUrl),
    thumbnailImageUrl: resolveOptionalNewsImagePath(article.thumbnailImageUrl),
    sections: article.sections?.map((section) =>
      section.inlineImage
        ? {
            ...section,
            inlineImage: {
              ...section.inlineImage,
              src: resolveNewsImagePath(section.inlineImage.src),
            },
          }
        : section,
    ),
  };
}

const PUBLISHED_NEWS_ARTICLES: NewsArticle[] = [
  applyNewsSearchSeo(VECKAN_SOM_GATT_29_AUGUSTI_2026_ARTICLE),
  applyNewsSearchSeo(BORSSVERIGE_28_AUGUSTI_2026_ARTICLE),
  applyNewsSearchSeo(NORDEN_I_CENTRUM_28_AUGUSTI_2026_ARTICLE),
  applyNewsSearchSeo(USA_BORSEN_NVIDIA_NASDAQ_AI_RALLY_27_AUGUSTI_2026_ARTICLE),
  applyNewsSearchSeo(BORSSVERIGE_27_AUGUSTI_2026_ARTICLE),
  ...DEMO_NEWS_ARTICLES,
];

const RESOLVED_NEWS_ARTICLES: NewsArticle[] =
  PUBLISHED_NEWS_ARTICLES.map(resolveNewsArticleImages);

/**
 * Börsnyheter article source.
 * Published editorial content is assembled here from the current article and
 * the historical article registry in data/news-demo.ts.
 */
export function getNewsArticles(): NewsArticle[] {
  return RESOLVED_NEWS_ARTICLES;
}

export function getNewsArticleBySlug(slug: string): NewsArticle | undefined {
  return getNewsArticles().find((article) => article.slug === slug);
}

export function getNewsArticlesWithSlug(): NewsArticle[] {
  return getNewsArticles().filter((article) => Boolean(article.slug));
}

/** Internal detail href when the article has a slug; otherwise the external url. */
export function getNewsArticleHref(article: NewsArticle): string | null {
  if (article.slug) {
    return `/news/${article.slug}`;
  }

  return article.url;
}

export function isInternalNewsArticleHref(href: string) {
  return href.startsWith("/");
}
