/** Paths blocked from crawling in robots.txt (authenticated / private / non-public). */
export const ROBOTS_DISALLOW_PATHS = [
  "/login",
  "/register",
  "/forgot-password",
  "/reset-password",
  "/account",
  "/account/",
  "/dashboard",
  "/dashboard/",
  "/settings",
  "/messages",
  "/messages/",
  "/contacts",
  "/portfolio",
  "/watchlist",
  "/goals",
  "/calendar",
  "/brain",
  "/forum/new",
  "/forum/demo-interactions-preview",
  "/profile/",
  "/auth/",
  "/api/",
] as const;
