-- Followable DAX 40 and Nasdaq-100 companies.
--
-- Index membership stays in the typed catalog. This migration only creates
-- company and primary-instrument rows so a follow can be stored.
-- Existing slugs are left untouched. No company_sources rows are inserted,
-- so a follow does not enqueue official ingestion.

insert into public.companies (
  slug,
  name,
  country_code
)
values
  ('siemens', 'Siemens', 'DE'),
  ('sap', 'SAP', 'DE'),
  ('allianz', 'Allianz', 'DE'),
  ('siemens-energy', 'Siemens Energy', 'DE'),
  ('airbus', 'Airbus', 'NL'),
  ('deutsche-telekom', 'Deutsche Telekom', 'DE'),
  ('infineon', 'Infineon', 'DE'),
  ('munich-re', 'Münchener Rück', 'DE'),
  ('deutsche-bank', 'Deutsche Bank', 'DE'),
  ('rheinmetall', 'Rheinmetall', 'DE'),
  ('dhl', 'DHL Group', 'DE'),
  ('deutsche-boerse', 'Deutsche Börse', 'DE'),
  ('bayer', 'Bayer', 'DE'),
  ('basf', 'BASF', 'DE'),
  ('eon', 'E.ON', 'DE'),
  ('rwe', 'RWE', 'DE'),
  ('mercedes-benz', 'Mercedes-Benz Group', 'DE'),
  ('adidas', 'Adidas', 'DE'),
  ('daimler-truck', 'Daimler Truck', 'DE'),
  ('heidelberg-materials', 'Heidelberg Materials', 'DE'),
  ('mtu', 'MTU Aero Engines', 'DE'),
  ('bmw', 'BMW', 'DE'),
  ('fresenius', 'Fresenius', 'DE'),
  ('merck-kgaa', 'Merck KGaA', 'DE'),
  ('commerzbank', 'Commerzbank', 'DE'),
  ('volkswagen', 'Volkswagen', 'DE'),
  ('hannover-re', 'Hannover Rück', 'DE'),
  ('vonovia', 'Vonovia', 'DE'),
  ('siemens-healthineers', 'Siemens Healthineers', 'DE'),
  ('symrise', 'Symrise', 'DE'),
  ('henkel', 'Henkel', 'DE'),
  ('gea', 'GEA Group', 'DE'),
  ('fresenius-medical-care', 'Fresenius Medical Care', 'DE'),
  ('qiagen', 'Qiagen', 'NL'),
  ('hochtief', 'Hochtief', 'DE'),
  ('continental', 'Continental', 'DE'),
  ('brenntag', 'Brenntag', 'DE'),
  ('beiersdorf', 'Beiersdorf', 'DE'),
  ('scout24', 'Scout24', 'DE'),
  ('zalando', 'Zalando', 'DE'),
  ('apple', 'Apple Inc.', 'US'),
  ('airbnb', 'Airbnb, Inc.', 'US'),
  ('adobe', 'Adobe Inc.', 'US'),
  ('analog-devices', 'Analog Devices, Inc.', 'US'),
  ('automatic-data-processing', 'Automatic Data Processing, Inc.', 'US'),
  ('autodesk', 'Autodesk, Inc.', 'US'),
  ('american-electric-power', 'American Electric Power Company, Inc.', 'US'),
  ('astera-labs', 'Astera Labs, Inc.', 'US'),
  ('alnylam-pharmaceuticals', 'Alnylam Pharmaceuticals, Inc.', 'US'),
  ('applied-materials', 'Applied Materials, Inc.', 'US'),
  ('advanced-micro-devices', 'Advanced Micro Devices, Inc.', 'US'),
  ('amgen', 'Amgen Inc.', 'US'),
  ('amazon', 'Amazon.com, Inc.', 'US'),
  ('applovin', 'Applovin Corporation', 'US'),
  ('arm', 'Arm Holdings plc', 'US'),
  ('asml', 'ASML Holding N.V.', 'US'),
  ('broadcom', 'Broadcom Inc.', 'US'),
  ('axon-enterprise', 'Axon Enterprise, Inc.', 'US'),
  ('booking-holdings', 'Booking Holdings Inc.', 'US'),
  ('baker-hughes', 'Baker Hughes Company', 'US'),
  ('coca-cola-europacific-partners', 'Coca-Cola Europacific Partners plc', 'US'),
  ('cadence-design-systems', 'Cadence Design Systems, Inc.', 'US'),
  ('constellation-energy', 'Constellation Energy Corporation', 'US'),
  ('comcast', 'Comcast Corporation', 'US'),
  ('costco', 'Costco Wholesale Corporation', 'US'),
  ('copart', 'Copart, Inc.', 'US'),
  ('crowdstrike', 'CrowdStrike Holdings, Inc.', 'US'),
  ('coreweave', 'CoreWeave, Inc.', 'US'),
  ('cisco-systems', 'Cisco Systems, Inc.', 'US'),
  ('csx', 'CSX Corporation', 'US'),
  ('cintas', 'Cintas Corporation', 'US'),
  ('doordash', 'DoorDash, Inc.', 'US'),
  ('datadog', 'Datadog, Inc.', 'US'),
  ('dexcom', 'DexCom, Inc.', 'US'),
  ('exelon', 'Exelon Corporation', 'US'),
  ('diamondback-energy', 'Diamondback Energy, Inc.', 'US'),
  ('fastenal', 'Fastenal Company', 'US'),
  ('ferrovial', 'Ferrovial N.V.', 'US'),
  ('fortinet', 'Fortinet, Inc.', 'US'),
  ('ge-healthcare-technologies', 'GE HealthCare Technologies Inc.', 'US'),
  ('gilead-sciences', 'Gilead Sciences, Inc.', 'US'),
  ('alphabet', 'Alphabet Inc.', 'US'),
  ('honeywell-international', 'Honeywell International Inc.', 'US'),
  ('honeywell-aerospace', 'Honeywell Aerospace Inc.', 'US'),
  ('idexx-laboratories', 'IDEXX Laboratories, Inc.', 'US'),
  ('intel', 'Intel Corporation', 'US'),
  ('intuit', 'Intuit Inc.', 'US'),
  ('intuitive-surgical', 'Intuitive Surgical, Inc.', 'US'),
  ('keurig-dr-pepper', 'Keurig Dr Pepper Inc.', 'US'),
  ('kla', 'KLA Corporation ', 'US'),
  ('linde', 'Linde plc', 'US'),
  ('lumentum', 'Lumentum Holdings Inc.', 'US'),
  ('lam-research', 'Lam Research Corporation', 'US'),
  ('marriott-international', 'Marriott International', 'US'),
  ('microchip-technology', 'Microchip Technology Incorporated', 'US'),
  ('mondelez-international', 'Mondelez International, Inc.', 'US'),
  ('mercadolibre', 'MercadoLibre, Inc.', 'US'),
  ('meta-platforms', 'Meta Platforms, Inc.', 'US'),
  ('monster-beverage', 'Monster Beverage Corporation', 'US'),
  ('monolithic-power-systems', 'Monolithic Power Systems, Inc.', 'US'),
  ('marvell-technology', 'Marvell Technology, Inc.', 'US'),
  ('microsoft', 'Microsoft Corporation', 'US'),
  ('strategy-inc', 'Strategy Inc', 'US'),
  ('micron-technology', 'Micron Technology, Inc.', 'US'),
  ('nebius', 'Nebius Group N.V.', 'US'),
  ('netflix', 'Netflix, Inc.', 'US'),
  ('nvidia', 'NVIDIA Corporation', 'US'),
  ('nxp-semiconductors', 'NXP Semiconductors N.V.', 'US'),
  ('old-dominion-freight-line', 'Old Dominion Freight Line, Inc.', 'US'),
  ('oreilly-automotive', 'O''Reilly Automotive, Inc.', 'US'),
  ('palo-alto-networks', 'Palo Alto Networks, Inc.', 'US'),
  ('paychex', 'Paychex, Inc.', 'US'),
  ('paccar', 'PACCAR Inc.', 'US'),
  ('pdd-holdings', 'PDD Holdings Inc.', 'US'),
  ('pepsico', 'PepsiCo, Inc.', 'US'),
  ('palantir-technologies', 'Palantir Technologies Inc.', 'US'),
  ('paypal', 'PayPal Holdings, Inc.', 'US'),
  ('qualcomm', 'QUALCOMM Incorporated', 'US'),
  ('regeneron-pharmaceuticals', 'Regeneron Pharmaceuticals, Inc.', 'US'),
  ('rocket-lab', 'Rocket Lab Corporation', 'US'),
  ('roper-technologies', 'Roper Technologies, Inc.', 'US'),
  ('ross-stores', 'Ross Stores, Inc.', 'US'),
  ('starbucks', 'Starbucks Corporation', 'US'),
  ('shopify', 'Shopify Inc.', 'US'),
  ('sandisk', 'Sandisk Corporation', 'US'),
  ('synopsys', 'Synopsys, Inc.', 'US'),
  ('space-exploration-technologies', 'Space Exploration Technologies Corp.', 'US'),
  ('seagate-technology', 'Seagate Technology Holdings PLC', 'US'),
  ('teradyne', 'Teradyne, Inc.', 'US'),
  ('t-mobile-us', 'T-Mobile US, Inc.', 'US'),
  ('thomson-reuters', 'Thomson Reuters Corp', 'US'),
  ('tesla', 'Tesla, Inc. ', 'US'),
  ('take-two-interactive-software', 'Take-Two Interactive Software, Inc.', 'US'),
  ('texas-instruments', 'Texas Instruments Incorporated', 'US'),
  ('vertex-pharmaceuticals', 'Vertex Pharmaceuticals Incorporated', 'US'),
  ('warner-bros-discovery', 'Warner Bros. Discovery, Inc.', 'US'),
  ('workday', 'Workday, Inc.', 'US'),
  ('western-digital', 'Western Digital Corporation', 'US'),
  ('walmart', 'Walmart Inc.', 'US'),
  ('xcel-energy', 'Xcel Energy Inc.', 'US')
on conflict (slug) do nothing;

insert into public.company_instruments (
  company_id,
  symbol,
  exchange_name,
  exchange_mic,
  currency_code,
  tradingview_symbol,
  is_primary,
  is_active
)
select
  company.id,
  seed.symbol,
  seed.exchange_name,
  seed.exchange_mic,
  seed.currency_code,
  seed.tradingview_symbol,
  true,
  true
from (
  values
    ('siemens', 'SIE', 'Xetra', 'XETR', 'EUR', 'XETR:SIE'),
    ('sap', 'SAP', 'Xetra', 'XETR', 'EUR', 'XETR:SAP'),
    ('allianz', 'ALV', 'Xetra', 'XETR', 'EUR', 'XETR:ALV'),
    ('siemens-energy', 'ENR', 'Xetra', 'XETR', 'EUR', 'XETR:ENR'),
    ('airbus', 'AIR', 'Xetra', 'XETR', 'EUR', 'XETR:AIR'),
    ('deutsche-telekom', 'DTE', 'Xetra', 'XETR', 'EUR', 'XETR:DTE'),
    ('infineon', 'IFX', 'Xetra', 'XETR', 'EUR', 'XETR:IFX'),
    ('munich-re', 'MUV2', 'Xetra', 'XETR', 'EUR', 'XETR:MUV2'),
    ('deutsche-bank', 'DBK', 'Xetra', 'XETR', 'EUR', 'XETR:DBK'),
    ('rheinmetall', 'RHM', 'Xetra', 'XETR', 'EUR', 'XETR:RHM'),
    ('dhl', 'DHL', 'Xetra', 'XETR', 'EUR', 'XETR:DHL'),
    ('deutsche-boerse', 'DB1', 'Xetra', 'XETR', 'EUR', 'XETR:DB1'),
    ('bayer', 'BAYN', 'Xetra', 'XETR', 'EUR', 'XETR:BAYN'),
    ('basf', 'BAS', 'Xetra', 'XETR', 'EUR', 'XETR:BAS'),
    ('eon', 'EOAN', 'Xetra', 'XETR', 'EUR', 'XETR:EOAN'),
    ('rwe', 'RWE', 'Xetra', 'XETR', 'EUR', 'XETR:RWE'),
    ('mercedes-benz', 'MBG', 'Xetra', 'XETR', 'EUR', 'XETR:MBG'),
    ('adidas', 'ADS', 'Xetra', 'XETR', 'EUR', 'XETR:ADS'),
    ('daimler-truck', 'DTG', 'Xetra', 'XETR', 'EUR', 'XETR:DTG'),
    ('heidelberg-materials', 'HEI', 'Xetra', 'XETR', 'EUR', 'XETR:HEI'),
    ('mtu', 'MTX', 'Xetra', 'XETR', 'EUR', 'XETR:MTX'),
    ('bmw', 'BMW', 'Xetra', 'XETR', 'EUR', 'XETR:BMW'),
    ('fresenius', 'FRE', 'Xetra', 'XETR', 'EUR', 'XETR:FRE'),
    ('merck-kgaa', 'MRK', 'Xetra', 'XETR', 'EUR', 'XETR:MRK'),
    ('commerzbank', 'CBK', 'Xetra', 'XETR', 'EUR', 'XETR:CBK'),
    ('volkswagen', 'VOW3', 'Xetra', 'XETR', 'EUR', 'XETR:VOW3'),
    ('hannover-re', 'HNR1', 'Xetra', 'XETR', 'EUR', 'XETR:HNR1'),
    ('vonovia', 'VNA', 'Xetra', 'XETR', 'EUR', 'XETR:VNA'),
    ('siemens-healthineers', 'SHL', 'Xetra', 'XETR', 'EUR', 'XETR:SHL'),
    ('symrise', 'SY1', 'Xetra', 'XETR', 'EUR', 'XETR:SY1'),
    ('henkel', 'HEN3', 'Xetra', 'XETR', 'EUR', 'XETR:HEN3'),
    ('gea', 'G1A', 'Xetra', 'XETR', 'EUR', 'XETR:G1A'),
    ('fresenius-medical-care', 'FME', 'Xetra', 'XETR', 'EUR', 'XETR:FME'),
    ('qiagen', 'QIA', 'Xetra', 'XETR', 'EUR', 'XETR:QIA'),
    ('hochtief', 'HOT', 'Xetra', 'XETR', 'EUR', 'XETR:HOT'),
    ('continental', 'CON', 'Xetra', 'XETR', 'EUR', 'XETR:CON'),
    ('brenntag', 'BNR', 'Xetra', 'XETR', 'EUR', 'XETR:BNR'),
    ('beiersdorf', 'BEI', 'Xetra', 'XETR', 'EUR', 'XETR:BEI'),
    ('scout24', 'G24', 'Xetra', 'XETR', 'EUR', 'XETR:G24'),
    ('zalando', 'ZAL', 'Xetra', 'XETR', 'EUR', 'XETR:ZAL'),
    ('apple', 'AAPL', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:AAPL'),
    ('airbnb', 'ABNB', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ABNB'),
    ('adobe', 'ADBE', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ADBE'),
    ('analog-devices', 'ADI', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ADI'),
    ('automatic-data-processing', 'ADP', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ADP'),
    ('autodesk', 'ADSK', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ADSK'),
    ('american-electric-power', 'AEP', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:AEP'),
    ('astera-labs', 'ALAB', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ALAB'),
    ('alnylam-pharmaceuticals', 'ALNY', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ALNY'),
    ('applied-materials', 'AMAT', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:AMAT'),
    ('advanced-micro-devices', 'AMD', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:AMD'),
    ('amgen', 'AMGN', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:AMGN'),
    ('amazon', 'AMZN', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:AMZN'),
    ('applovin', 'APP', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:APP'),
    ('arm', 'ARM', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ARM'),
    ('asml', 'ASML', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ASML'),
    ('broadcom', 'AVGO', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:AVGO'),
    ('axon-enterprise', 'AXON', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:AXON'),
    ('booking-holdings', 'BKNG', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:BKNG'),
    ('baker-hughes', 'BKR', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:BKR'),
    ('coca-cola-europacific-partners', 'CCEP', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:CCEP'),
    ('cadence-design-systems', 'CDNS', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:CDNS'),
    ('constellation-energy', 'CEG', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:CEG'),
    ('comcast', 'CMCSA', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:CMCSA'),
    ('costco', 'COST', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:COST'),
    ('copart', 'CPRT', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:CPRT'),
    ('crowdstrike', 'CRWD', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:CRWD'),
    ('coreweave', 'CRWV', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:CRWV'),
    ('cisco-systems', 'CSCO', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:CSCO'),
    ('csx', 'CSX', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:CSX'),
    ('cintas', 'CTAS', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:CTAS'),
    ('doordash', 'DASH', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:DASH'),
    ('datadog', 'DDOG', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:DDOG'),
    ('dexcom', 'DXCM', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:DXCM'),
    ('exelon', 'EXC', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:EXC'),
    ('diamondback-energy', 'FANG', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:FANG'),
    ('fastenal', 'FAST', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:FAST'),
    ('ferrovial', 'FER', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:FER'),
    ('fortinet', 'FTNT', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:FTNT'),
    ('ge-healthcare-technologies', 'GEHC', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:GEHC'),
    ('gilead-sciences', 'GILD', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:GILD'),
    ('alphabet', 'GOOGL', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:GOOGL'),
    ('honeywell-international', 'HON', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:HON'),
    ('honeywell-aerospace', 'HONA', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:HONA'),
    ('idexx-laboratories', 'IDXX', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:IDXX'),
    ('intel', 'INTC', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:INTC'),
    ('intuit', 'INTU', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:INTU'),
    ('intuitive-surgical', 'ISRG', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ISRG'),
    ('keurig-dr-pepper', 'KDP', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:KDP'),
    ('kla', 'KLAC', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:KLAC'),
    ('linde', 'LIN', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:LIN'),
    ('lumentum', 'LITE', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:LITE'),
    ('lam-research', 'LRCX', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:LRCX'),
    ('marriott-international', 'MAR', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:MAR'),
    ('microchip-technology', 'MCHP', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:MCHP'),
    ('mondelez-international', 'MDLZ', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:MDLZ'),
    ('mercadolibre', 'MELI', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:MELI'),
    ('meta-platforms', 'META', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:META'),
    ('monster-beverage', 'MNST', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:MNST'),
    ('monolithic-power-systems', 'MPWR', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:MPWR'),
    ('marvell-technology', 'MRVL', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:MRVL'),
    ('microsoft', 'MSFT', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:MSFT'),
    ('strategy-inc', 'MSTR', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:MSTR'),
    ('micron-technology', 'MU', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:MU'),
    ('nebius', 'NBIS', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:NBIS'),
    ('netflix', 'NFLX', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:NFLX'),
    ('nvidia', 'NVDA', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:NVDA'),
    ('nxp-semiconductors', 'NXPI', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:NXPI'),
    ('old-dominion-freight-line', 'ODFL', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ODFL'),
    ('oreilly-automotive', 'ORLY', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ORLY'),
    ('palo-alto-networks', 'PANW', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:PANW'),
    ('paychex', 'PAYX', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:PAYX'),
    ('paccar', 'PCAR', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:PCAR'),
    ('pdd-holdings', 'PDD', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:PDD'),
    ('pepsico', 'PEP', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:PEP'),
    ('palantir-technologies', 'PLTR', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:PLTR'),
    ('paypal', 'PYPL', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:PYPL'),
    ('qualcomm', 'QCOM', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:QCOM'),
    ('regeneron-pharmaceuticals', 'REGN', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:REGN'),
    ('rocket-lab', 'RKLB', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:RKLB'),
    ('roper-technologies', 'ROP', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ROP'),
    ('ross-stores', 'ROST', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:ROST'),
    ('starbucks', 'SBUX', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:SBUX'),
    ('shopify', 'SHOP', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:SHOP'),
    ('sandisk', 'SNDK', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:SNDK'),
    ('synopsys', 'SNPS', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:SNPS'),
    ('space-exploration-technologies', 'SPCX', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:SPCX'),
    ('seagate-technology', 'STX', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:STX'),
    ('teradyne', 'TER', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:TER'),
    ('t-mobile-us', 'TMUS', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:TMUS'),
    ('thomson-reuters', 'TRI', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:TRI'),
    ('tesla', 'TSLA', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:TSLA'),
    ('take-two-interactive-software', 'TTWO', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:TTWO'),
    ('texas-instruments', 'TXN', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:TXN'),
    ('vertex-pharmaceuticals', 'VRTX', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:VRTX'),
    ('warner-bros-discovery', 'WBD', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:WBD'),
    ('workday', 'WDAY', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:WDAY'),
    ('western-digital', 'WDC', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:WDC'),
    ('walmart', 'WMT', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:WMT'),
    ('xcel-energy', 'XEL', 'Nasdaq', 'XNAS', 'USD', 'NASDAQ:XEL')
) as seed(slug, symbol, exchange_name, exchange_mic, currency_code, tradingview_symbol)
join public.companies company on company.slug = seed.slug
on conflict (company_id, exchange_name, symbol) do nothing;
